### ISSUE TITLE
java.lang.IllegalStateException: Request object no longer valid

### ISSUE THREAD

**Issue by vbarrier** [Atmosphere/atmosphere#1052]
With enable protocol set to true, sometimes we get : 

``` java
013-04-26 16:28:49,916 [http-8080-exec-3] INFO  web.Timer  - Uncached request for /icescrum/grails/project/browse.dispatch took 0:00:00.867
2013-04-26 16:28:52,204 [http-8080-exec-5] DEBUG interceptor.OnDisconnectInterceptor  - AtmosphereResource 16e75f7c-692f-464d-baa9-89b191747a5d disconnected
2013-04-26 16:28:52,205 [http-8080-exec-5] DEBUG atmosphere.IceScrumAtmosphereEventListener  - user anonymous disconnected with UUID 16e75f7c-692f-464d-baa9-89b191747a5d
2013-04-26 16:28:52,225 [http-8080-exec-4] DEBUG cpr.AsynchronousProcessor  - Cancelling the connection for AtmosphereResource 16e75f7c-692f-464d-baa9-89b191747a5d
2013-04-26 16:28:52,226 [http-8080-exec-4] DEBUG cpr.DefaultBroadcasterFactory  - Removing Broadcaster /stream/app/* factory size now 0 
2013-04-26 16:28:52,226 [http-8080-exec-4] DEBUG cpr.DefaultBroadcaster  - This Broadcaster has been destroyed and cannot be used /stream/app/* by invoking removeAtmosphereResource(AtmosphereResource r)
2013-04-26 16:28:52,234 [http-8080-exec-5] ERROR cpr.AtmosphereFramework  - AtmosphereFramework exception
java.lang.IllegalStateException: Request object no longer valid. This object has been cancelled
    at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:509)
    at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:529)
    at org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:59)
    at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:278)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:244)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:166)
    at org.atmosphere.container.TomcatCometSupport.service(TomcatCometSupport.java:115)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1342)
    at org.atmosphere.cpr.AtmosphereServlet.event(AtmosphereServlet.java:331)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilterEvent(ApplicationFilterChain.java:470)
    at org.apache.catalina.core.ApplicationFilterChain.doFilterEvent(ApplicationFilterChain.java:363)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:883)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:722)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2214)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by lexmi0412** [comment]
The issue still exists. We are using Atmosphere 2.6.1 and sometimes we get the same. 

The issue is thrown when we try to get the request from the AtmosphereResource from our custom Broadcastfilter.  

java.lang.IllegalStateException: Request object no longer valid. This object has been cancelled
	at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:422) ~[atmosphere-runtime-2.6.1.jar!/:2.6.1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.getRequest(AtmosphereResourceImpl.java:436) ~[atmosphere-runtime-2.6.1.jar!/:2.6.1]
