### ISSUE TITLE
[Tomcat/WebSocket] Deadlock detected in Atmosphere Scheduler

### ISSUE THREAD

**Issue by steffimueller** [Atmosphere/atmosphere#1264]
I use Atmosphere in a Servlet context for quite a bit of time. System work fine but when there is high traffic on my site all Atmosphere-Scheduler run into Monitor. Atmosphere-Shared-AsyncOp is also in Monitor. This is what I have analyzed with VisualVM.  

Here is the VisualVM Threads visualisation:
![visualvm_1 3 6](https://f.cloud.github.com/assets/5350431/1061436/5c23253e-11d6-11e3-847b-16eed55d8bac.jpg)

If you need I provide you with more configuration. What do you need th solve this?

Here is the Thread Dump: 

2013-08-31 02:33:35
Full thread dump Java HotSpot(TM) 64-Bit Server VM (23.25-b01 mixed mode):

``` java
"RMI TCP Connection(429)-85.176.58.104" - Thread t@1907
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
    - locked <4e367d62> (a java.io.BufferedInputStream)
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:535)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <40e4a1f2> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"RMI TCP Connection(432)-85.176.58.104" - Thread t@1906
   java.lang.Thread.State: RUNNABLE
    at sun.management.ThreadImpl.dumpThreads0(Native Method)
    at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
    at sun.reflect.GeneratedMethodAccessor2526.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:75)
    at sun.reflect.GeneratedMethodAccessor2369.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:279)
    at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:193)
    at com.sun.jmx.mbeanserver.ConvertingMethod.invokeWithOpenReturn(ConvertingMethod.java:175)
    at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:117)
    at com.sun.jmx.mbeanserver.MXBeanIntrospector.invokeM2(MXBeanIntrospector.java:54)
    at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
    at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
    at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
    at javax.management.StandardMBean.invoke(StandardMBean.java:405)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
    at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
    at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
    at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1487)
    at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
    at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1427)
    at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:848)
    at sun.reflect.GeneratedMethodAccessor2405.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    at sun.rmi.transport.Transport$1.run(Transport.java:177)
    at sun.rmi.transport.Transport$1.run(Transport.java:174)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:553)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <2da70ce1> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"RMI TCP Connection(430)-85.176.58.104" - Thread t@1894
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
    - locked <49539a1> (a java.io.BufferedInputStream)
    at java.io.FilterInputStream.read(FilterInputStream.java:83)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:535)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <40ac17a2> (a java.util.concurrent.ThreadPoolExecutor$Worker)


"Atmosphere-Shared-AsyncOp-283" - Thread t@1488
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:165)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:169)
    at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1027)
    at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1047)
    at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:921)
    at org.atmosphere.cpr.DefaultBroadcaster$3.run(DefaultBroadcaster.java:580)
    - locked <15cac788> (a org.atmosphere.cpr.AtmosphereResourceImpl)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <15fe5f34> (a java.util.concurrent.ThreadPoolExecutor$Worker)


"Atmosphere-Scheduler-5" - Thread t@151
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:165)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:992)
    at org.atmosphere.interceptor.HeartbeatInterceptor$1$1.call(HeartbeatInterceptor.java:104)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <3230487> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Atmosphere-Scheduler-4" - Thread t@150
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:165)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:992)
    at org.atmosphere.interceptor.HeartbeatInterceptor$1$1.call(HeartbeatInterceptor.java:104)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <4333842e> (a java.util.concurrent.ThreadPoolExecutor$Worker)


"http-nio-8080-exec-11" - Thread t@106
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.close(WsOutbound.java:273)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.apache.catalina.websocket.StreamInbound.closeOutboundConnection(StreamInbound.java:196)
    at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:162)
    at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1686)
    - locked <266bb16b> (a org.apache.tomcat.util.net.NioChannel)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <1ff7015d> (a java.util.concurrent.ThreadPoolExecutor$Worker)


"Atmosphere-Scheduler-3" - Thread t@89
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:165)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:992)
    at org.atmosphere.interceptor.HeartbeatInterceptor$1$1.call(HeartbeatInterceptor.java:104)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <3c0f502> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Atmosphere-Scheduler-2" - Thread t@87
   java.lang.Thread.State: BLOCKED
    at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:476)
    - waiting to lock <15cac788> (a org.atmosphere.cpr.AtmosphereResourceImpl) owned by "Atmosphere-Shared-AsyncOp-283" t@1488
    at org.atmosphere.cpr.AsynchronousProcessor.timedout(AsynchronousProcessor.java:437)
    at org.atmosphere.cpr.AsynchronousProcessor$AsynchronousProcessorHook.timedOut(AsynchronousProcessor.java:633)
    at org.atmosphere.websocket.DefaultWebSocketProcessor.close(DefaultWebSocketProcessor.java:483)
    at org.atmosphere.container.TomcatWebSocketHandler.onClose(TomcatWebSocketHandler.java:80)
    at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:222)
    at org.apache.catalina.websocket.WsOutbound.doWriteBytes(WsOutbound.java:423)
    at org.apache.catalina.websocket.WsOutbound.doWriteText(WsOutbound.java:442)
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:174)
    - locked <243f01c7> (a org.apache.catalina.websocket.WsOutbound)
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:992)
    at org.atmosphere.interceptor.HeartbeatInterceptor$1$1.call(HeartbeatInterceptor.java:104)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <7d78563c> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Atmosphere-Scheduler-1" - Thread t@85
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:165)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:992)
    at org.atmosphere.interceptor.HeartbeatInterceptor$1$1.call(HeartbeatInterceptor.java:104)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <3a0cff59> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Atmosphere-Scheduler-0" - Thread t@84
   java.lang.Thread.State: BLOCKED
    at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:165)
    - waiting to lock <243f01c7> (a org.apache.catalina.websocket.WsOutbound) owned by "Atmosphere-Scheduler-2" t@87
    at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:49)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:199)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:168)
    at org.atmosphere.websocket.WebSocket.write(WebSocket.java:40)
    at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:574)
    at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:992)
    at org.atmosphere.interceptor.HeartbeatInterceptor$1$1.call(HeartbeatInterceptor.java:104)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

   Locked ownable synchronizers:
    - locked <1c328ef> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by ivanov35** [comment]
Hi,

I have a similar problem. The application reaches sometimes very high CPU consumption. I am using Tomcat 7.0.42, but in my case there is no blocking thread, just TIME_WAITING for Atmosphere-Scheduler-.
Do you know if this is a similar problem ?

**Comment by jfarcand** [comment]
@ivanov35 Unrelated
