### ISSUE TITLE
ERROR o.a.cpr.AsynchronousProcessor - No AtmosphereHandler found

### ISSUE THREAD

**Issue by vkumar9** [Atmosphere/atmosphere#1421]
Hi ,

I am new to the atmosphere framework . I am trying the sample chat application . The project has been compiled and packaged successfully . But it is giving exception on tomcat 7 . Below is the stack trace:

ERROR o.a.cpr.AsynchronousProcessor - No AtmosphereHandler found. Make sure you define it inside WEB-INF/atmosphere.xml or annotate using @___Service
Jan 7, 2014 11:10:09 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [AtmosphereServlet] in context with path [/atmos-alpha] threw exception
org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler found. Make sure you define it inside WEB-INF/atmosphere.xml or annotate using @___Service
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:146)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:123)
    at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:102)
    at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.doService(Tomcat7Servlet30SupportWithWebSocket.java:67)
    at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:98)
    at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1757)
    at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:201)
    at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:187)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

This exception is occurring when  i build the project using maven .
Otherwise ,it is working fine without maven .

**Comment by daocaorenbao** [comment]
How do you resolve the exception
