### ISSUE TITLE
Failed to start on weblogci 12.1.2.0.0

### ISSUE THREAD

**Issue by szeseong** [Atmosphere/atmosphere#1569]
Below log is the error log

``` java
Caused by: java.lang.UnsupportedOperationException: [HTTP:101388]The ServletContext was passed to the ServletContextListener.contextInitialized method of a ServletContextListener that was neither declared in web.xml or web-fragment.xml, nor annotated with javax.servlet.annotation.WebListener.

at weblogic.servlet.internal.WebAppServletContext.checkNotifyDynamicContext(WebAppServletContext.java:3917)
at weblogic.servlet.internal.WebAppServletContext.getServletRegistration(WebAppServletContext.java:3799)
at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:87)
at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:80)
at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.run(StubSecurityHelper.java:337)
```

**Comment by dadikovi** [comment]
Is it possible that the same issue appears in [IOUtils:255](https://github.com/Atmosphere/atmosphere/blob/124c9a075435973356cca3c7f5309152b4664abb/modules/runtime/src/main/java/org/atmosphere/util/IOUtils.java#L255) ?

**Comment by jfarcand** [comment]
@dadikovi Are you getting the exception? In any case pull request welcomed :-) (yes I suspect that could happens)
