### ISSUE TITLE
[Tomcat] NIO error when the websocket is closed

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1646]
Must workaround the issue
```java
java.io.IOException: Key must be cancelled
	at org.apache.coyote.http11.upgrade.UpgradeNioProcessor.writeToSocket(UpgradeNioProcessor.java:216)
	at org.apache.coyote.http11.upgrade.UpgradeNioProcessor.write(UpgradeNioProcessor.java:85)
	at org.apache.coyote.http11.upgrade.UpgradeOutbound.write(UpgradeOutbound.java:44)
	at org.apache.catalina.websocket.WsOutbound.doWriteBytes(WsOutbound.java:477)
	at org.apache.catalina.websocket.WsOutbound.doWriteText(WsOutbound.java:529)
	at org.apache.catalina.websocket.WsOutbound.doFlush(WsOutbound.java:267)
	at org.apache.catalina.websocket.WsOutbound.close(WsOutbound.java:349)
	at org.atmosphere.container.version.TomcatWebSocket.close(TomcatWebSocket.java:84)
	at org.atmosphere.container.version.TomcatWebSocket.close(TomcatWebSocket.java:75)
	at org.atmosphere.cpr.AtmosphereResponse$2.close(AtmosphereResponse.java:563)
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:452)
	at org.atmosphere.cpr.AsynchronousProcessor.endRequest(AsynchronousProcessor.java:548)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.executeClose(DefaultWebSocketProcessor.java:676)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.close(DefaultWebSocketProcessor.java:628)
	at org.atmosphere.container.TomcatWebSocketHandler.onClose(TomcatWebSocketHandler.java:86)
	at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:226)
	at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:229)
	at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:57)
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:222)
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:187)
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:42)
	at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:509)
	at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:969)
	at org.atmosphere.interceptor.HeartbeatInterceptor$4.call(HeartbeatInterceptor.java:320)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
```

**Comment by jfarcand** [comment]
The `websocket.close()` is no longer invoked with the latest 2.2.4 version of [DefaultWebSocketProcessor](http://goo.gl/EiR5Tb)

**Comment by jfarcand** [comment]
Since it's a Tomcat issue, closing.
