### ISSUE TITLE
[Tomcat] Possible NPE on setAttribute

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1806]
As reported in #1770

``` java
java.lang.NullPointerException
    at org.apache.catalina.connector.Request.notifyAttributeAssigned(Request.java:1482)
    at org.apache.catalina.connector.Request.setAttribute(Request.java:1472)
    at org.apache.catalina.connector.RequestFacade.setAttribute(RequestFacade.java:539)
    at org.atmosphere.cpr.AtmosphereRequest.setAttribute(AtmosphereRequest.java:693)
    at org.atmosphere.interceptor.IdleResourceInterceptor.idleResources(IdleResourceInterceptor.java:89)
    at org.atmosphere.interceptor.IdleResourceInterceptor$1.run(IdleResourceInterceptor.java:69)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by Artur-** [comment]
With this change, each and every push request when using long polling with Tomcat 7 logs
```

Feb 17, 2015 1:27:06 PM org.atmosphere.cpr.AtmosphereRequest setAttribute
WARNING: 
java.lang.NullPointerException
	at org.apache.catalina.connector.Request.notifyAttributeAssigned(Request.java:1547)
	at org.apache.catalina.connector.Request.setAttribute(Request.java:1538)
	at org.apache.catalina.connector.RequestFacade.setAttribute(RequestFacade.java:541)
	at javax.servlet.ServletRequestWrapper.setAttribute(ServletRequestWrapper.java:239)
	at org.atmosphere.cpr.AtmosphereRequest.setAttribute(AtmosphereRequest.java:694)
	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:893)
	at org.atmosphere.cpr.DefaultBroadcaster$3.run(DefaultBroadcaster.java:519)
```

This used to be ignored/logged as trace in DefaultBroadcaster

```
            try {
                request.setAttribute(FrameworkConfig.MESSAGE_WRITTEN, "true");
            } catch (NullPointerException ex) {
                // GlassFish and Tomcat may have recycled the request at that moment so the operation will fail.
                // In that case we don't cache the message as it has been successfully written or cached later
                // in the code.
                logger.trace("NPE after the message has been written for {}", r.uuid());
            }
```

But has now become a WARNING

**Comment by jfarcand** [comment]
@Artur- Tested with all Connectors (APR, BIO and NIO) and Tomcat 7.0.x without seeing the issue. It is probably related to how Vaadin implements the Atmosphere's support.

**Comment by ducciovigolo** [comment]
@Artur- Hi, do you have any news about this issue? I'm using vaadin 7.4.0 and I have the warn logging on my logs for some (not all) of my requests.
I'm using Transport.LONG_POLLING with Tomcat 7.0.50

**Comment by Artur-** [comment]
It's fixed both in Atmosphere and will be in Vaadin 7.4.1

**Comment by ducciovigolo** [comment]
Hi Artur,

thanks for your quick reply!

duccio
