### ISSUE TITLE
Reloading a context throws following exception

### ISSUE THREAD

**Issue by bertung** [Atmosphere/atmosphere#1826]
Reloading a web application context throws the following exception, and socket connection can not be recovered with the persistent session reloaded from disk. Is this by design?
```java
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.atmosphere.cpr.DefaultBroadcaster.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1612)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at org.atmosphere.util.IOUtils.loadClass(IOUtils.java:308)
	at org.atmosphere.cpr.AtmosphereFramework.configureBroadcasterFactory(AtmosphereFramework.java:1161)
	at org.atmosphere.cpr.AtmosphereFramework.getBroadcasterFactory(AtmosphereFramework.java:2110)
	at org.atmosphere.cpr.AtmosphereConfig.getBroadcasterFactory(AtmosphereConfig.java:188)
	at org.atmosphere.cpr.AtmosphereResourceImpl.getBroadcaster(AtmosphereResourceImpl.java:453)
	at org.atmosphere.cpr.AtmosphereResourceImpl.getBroadcaster(AtmosphereResourceImpl.java:440)
	at com.neurokernel.server.task.RuntimeSocket.findContext(RuntimeSocket.java:195)
	at com.neurokernel.server.task.RuntimeSocket.onTextMessage(RuntimeSocket.java:221)
	at org.atmosphere.websocket.WebSocketProcessor$WebSocketHandlerProxy.onTextMessage(WebSocketProcessor.java:180)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeInterceptors(DefaultWebSocketProcessor.java:396)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeInterceptors(DefaultWebSocketProcessor.java:352)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:432)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:793)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:535)
	at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:104)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1721)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jfarcand** [comment]
Fixed by https://github.com/Atmosphere/atmosphere/commit/9a05e5ef1817b906b58e60029a98ef92977f25d3
