### ISSUE TITLE
[JBossWeb] Read Operation Block When APR is enabled

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1843]
As reported [here](https://groups.google.com/d/msg/atmosphere-framework/l5rlmBrCRq8/he8648OQisgJ)
```java
2015-01-20 15:20:20,765 WARN  [org.atmosphere.util.IOUtils] : ClientAbortException:  java.net.SocketTimeoutException: JBWEB002011: Socket read failed
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:359) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:422) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:381) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:193) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283) [rt.jar:1.7.0_45]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325) [rt.jar:1.7.0_45]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) [rt.jar:1.7.0_45]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) [rt.jar:1.7.0_45]
        at java.io.BufferedReader.read1(BufferedReader.java:203) [rt.jar:1.7.0_45]
        at java.io.BufferedReader.read(BufferedReader.java:279) [rt.jar:1.7.0_45]
        at java.io.Reader.read(Reader.java:140) [rt.jar:1.7.0_45]
        at org.atmosphere.util.IOUtils.readEntirelyAsString(IOUtils.java:156) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.util.IOUtils.readEntirely(IOUtils.java:114) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.primefaces.push.impl.PushEndpointHandlerProxy.onRequest(PushEndpointHandlerProxy.java:150) [primefaces-5.1.jar:5.1]
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.container.JBossWebCometSupport.service(JBossWebCometSupport.java:91) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2079) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:570) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:215) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.container.JBossWebSocketHandler.onSocketOpened(JBossWebSocketHandler.java:73) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.jboss.as.websockets.servlet.WebSocketServlet.event(WebSocketServlet.java:157) [jboss-as-websockets-0.5-cursor.jar:]
        at org.atmosphere.container.JBossWebSocketSupport.dispatch(JBossWebSocketSupport.java:80) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.atmosphere.cpr.AtmosphereServlet.event(AtmosphereServlet.java:316) [atmosphere-runtime-native-2.2.5-20150107.175549-2.jar:2.2.5-SNAPSHOT]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilterEvent(ApplicationFilterChain.java:458) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.core.ApplicationFilterChain.doFilterEvent(ApplicationFilterChain.java:364) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:228) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.3.2.Final-redhat-SNAPSHOT.jar:7.3.2.Final-redhat-SNAPSHOT]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:880) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:607) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2056) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]
Caused by: java.net.SocketTimeoutException: JBWEB002011: Socket read failed
        at org.apache.coyote.http11.InternalAprInputBuffer.fill(InternalAprInputBuffer.java:828) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.coyote.http11.InternalAprInputBuffer$SocketInputBuffer.doRead(InternalAprInputBuffer.java:881) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.coyote.http11.InternalAprInputBuffer.doRead(InternalAprInputBuffer.java:769) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.coyote.Request.doRead(Request.java:438) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:349) [jbossweb-7.3.1.Final-redhat-1.jar:7.3.1.Final-redhat-1]
        ... 36 more
```

**Comment by jfarcand** [comment]
JBoss EAP APR I/O read operation will block `20 000` when there are no body to read and a `GET` is sent and will throw:
```java
6:46:54,016 WARN  [org.atmosphere.interceptor.HeartbeatInterceptor] (http-/127.0.0.1:8080-4) : ClientAbortException:  java.net.SocketTimeoutException: JBWEB002011: Socket read failed
	at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:351) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
	at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:422) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:373) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:193) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283) [rt.jar:1.7.0_75]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325) [rt.jar:1.7.0_75]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) [rt.jar:1.7.0_75]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) [rt.jar:1.7.0_75]
	at java.io.BufferedReader.read1(BufferedReader.java:203) [rt.jar:1.7.0_75]
	at java.io.BufferedReader.read(BufferedReader.java:279) [rt.jar:1.7.0_75]
	at java.io.Reader.read(Reader.java:140) [rt.jar:1.7.0_75]
	at org.atmosphere.util.IOUtils.readEntirelyAsString(IOUtils.java:156) [atmosphere-runtime-native-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
	at org.atmosphere.interceptor.HeartbeatInterceptor.inspect(HeartbeatInterceptor.java:185) [atmosphere-runtime-native-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
```
The workaround consists of not executing read operation when the HTTP method is a get.
