### ISSUE TITLE
A lot of java.net.SocketException: Broken pipe exceptions

### ISSUE THREAD

**Issue by dmitry-treskunov** [Atmosphere/atmosphere#1852]
In the logs I see a lot of exceptions like this:

```
[2015-01-31 13:19:04,052]  ERROR [io-8443-exec-51] - .container.TomcatWebSocketUtil -  
java.lang.RuntimeException: java.net.SocketException: Broken pipe
	at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:984)
	at org.atmosphere.interceptor.PaddingAtmosphereInterceptor.writePadding(PaddingAtmosphereInterceptor.java:79)
	at org.atmosphere.interceptor.PaddingAtmosphereInterceptor.access$000(PaddingAtmosphereInterceptor.java:44)
	at org.atmosphere.interceptor.PaddingAtmosphereInterceptor$ForcePreSuspend.onPreSuspend(PaddingAtmosphereInterceptor.java:150)
	at org.atmosphere.cpr.AtmosphereResourceImpl.onPreSuspend(AtmosphereResourceImpl.java:703)
	at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:354)
	at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:324)
	at jetbrains.buildServer.push.impl.atmosphere.AtmosphereHandler.onRequest(AtmosphereHandler.java:43)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104)
	at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2079)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:570)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:215)
	at org.atmosphere.container.TomcatWebSocketHandler.onOpen(TomcatWebSocketHandler.java:72)
	at org.apache.catalina.websocket.StreamInbound.onUpgradeComplete(StreamInbound.java:251)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:646)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:377)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:363)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:830)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:801)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:136)
	at org.apache.coyote.http11.upgrade.UpgradeBioProcessor.write(UpgradeBioProcessor.java:61)
	at org.apache.coyote.http11.upgrade.UpgradeOutbound.write(UpgradeOutbound.java:44)
	at org.apache.catalina.websocket.WsOutbound.doWriteBytes(WsOutbound.java:482)
	at org.apache.catalina.websocket.WsOutbound.doWriteText(WsOutbound.java:529)
	at org.apache.catalina.websocket.WsOutbound.writeTextMessage(WsOutbound.java:221)
	at org.atmosphere.container.version.TomcatWebSocket.write(TomcatWebSocket.java:57)
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:222)
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:187)
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:42)
	at org.atmosphere.cpr.AtmosphereResponse$2.write(AtmosphereResponse.java:515)
	at org.atmosphere.cpr.AtmosphereResponse.write(AtmosphereResponse.java:975)
	... 22 more
```

Is it ok?

**Comment by jfarcand** [comment]
@dmitry-treskunov Yes, it just means the connection was remotely closed.

**Comment by dmitry-treskunov** [comment]
It happens during connection opening, as I see from stacktrace.  

Maybe it doesn't make sense to log it with ERROR level.

**Comment by jfarcand** [comment]
Done my master.

**Comment by milmoe** [comment]
Do we know how to handle these exception?
