### ISSUE TITLE
No AtmosphereHandler maps request for

### ISSUE THREAD

**Issue by Aram89** [Atmosphere/atmosphere#1891]
Hi, I am new in Atmosphere, I want to use @ManagedService, but getting 
org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler maps request for /
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:211)
	at org.atmosphere.container.TomcatWebSocketHandler.onOpen(TomcatWebSocketHandler.java:72)
	at org.apache.catalina.websocket.StreamInbound.onUpgradeComplete(StreamInbound.java:251)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:642)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1720)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745) 
exception,  I am using Tomcat 7. Please help me to solve the problem.

**Comment by jfarcand** [comment]
Please use the mailing list: https://groups.google.com/group/atmosphere-framework?pli=1
