### ISSUE TITLE
long-polling cuases IllegalStateException: "STREAM"

### ISSUE THREAD

**Issue by FizzerWL** [Atmosphere/atmosphere#1894]
I recently integrated Atmosphere with my project, and found that I was getting this exception when calling getWriter:  java.lang.IllegalStateException: STREAM at org.eclipse.jetty.server.Response.getWriter(Response.java:920)

The strange thing is that these exceptions were coming from requests that had nothing to do with Atmosphere.  However, I have been able to determine that somehow Atmosphere is causing them, and only when using the long-polling transport.

I made a repro project to demonstrate this error.  You can download it here: https://d32kaghj56y4ei.cloudfront.net/other/AtmosphereIllegalStateException.zip

This repro project is based off the atmospherehandler-pubsub sample.  I only made four changes:

 - Change 1: long-polling selected by default in the html: <option id="long-polling" value="long-polling" selected="selected">long-polling</option>
 - Change 2: The topic input box defaults to "test" and the connect button auto clicks itself after page loads: setTimeout(connect, 50);
 - Change 3: In onOpen, the page redirects to /static:  request.onOpen = function() { setTimeout(function() { window.location = '/static'; }, 100); };
 - Change 4: A new page was added at /static, which simply writes out a script to redirect back to the first page:   
 
```java 
@WebServlet("/static")
public class StaticPage extends HttpServlet {
	@Override
	public void doGet(HttpServletRequest request, HttpServletResponse response) {
		try {
			response.setContentType("text/html");
			response.getWriter().write("Static page <script>setTimeout(function() { window.location = '/'; }, 100);</script>");
		} catch (Exception ex) {
			System.out.println("StaticPage error:");
			ex.printStackTrace();
		}
	}
}
```

You can run the repro project with "mvn package && mvn jetty:run".  Once you run it, and open it in your browser, your browser will rapidly redirect back and forth between the two pages.  If you let it run for a bit, it will stop and this error will be printed to stdout:
  
  StaticPage error:

```java
  java.lang.IllegalStateException: STREAM
    at org.eclipse.jetty.server.Response.getWriter(Response.java:920)
    at org.atmosphere.samples.pubsub.StaticPage.doGet(StaticPage.java:14)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
```

I am using Atmosphere 2.2.6, however I have verified that the same problem also happens in 2.2.5 and 2.3.0-SNAPSHOT.  It is running in Jetty 9.2.7. 

This problem does not happen when the transport is set to websocket.  Only long-polling seems to cause this problem.

I have verified this happens in several different browsers: Firefox 36.0 on Windows/Ubuntu, Chrome 41.0.2272.76/IE11 on Windows.  Although, interestingly, it seems to take longer to occur on some browsers than others.  For example, in Chrome can take a few minutes for the exception to occur, but in Firefox on Ubuntu it fails within the first few seconds every time.

**Comment by jfarcand** [comment]
@FizzerWL Please test.

**Comment by FizzerWL** [comment]
Hi,

You removed code that calls getOutputStream().close().  However, directly below that there is a call to "impl.cancel();", which also tries to close the output stream.  This is where I encountered the problem, not the code you removed.  Here is a stack trace:

  org.atmosphere.cpr.AtmosphereResponse.getOutputStream(AtmosphereResponse.java:598)
  org.atmosphere.cpr.AtmosphereResponse.closeStreamOrWriter(AtmosphereResponse.java:884)
  org.atmosphere.cpr.AtmosphereInterceptorWriter.close(AtmosphereInterceptorWriter.java:97)
  org.atmosphere.cpr.AtmosphereResponse$2.close(AtmosphereResponse.java:586)
  org.atmosphere.cpr.AtmosphereResponse.closeStreamOrWriter(AtmosphereResponse.java:884)
  org.atmosphere.cpr.AtmosphereInterceptorWriter.close(AtmosphereInterceptorWriter.java:97)
  org.atmosphere.cpr.AtmosphereResponse.close(AtmosphereResponse.java:872)
  org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:777)
  org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:482)
  org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:77)
  org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:319)
  org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:176)
  org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:105)
  org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
  org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:170)
  org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2076)
  org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:198)
  org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:184)
  javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

**Comment by jfarcand** [comment]
@FizzerWL My bad, fixed now

**Comment by jfarcand** [comment]
https://github.com/Atmosphere/atmosphere/commit/22d08c1bb70c956a3a67ea71b5ccbb2c265a7307
