### ISSUE TITLE
Guice extensions does not work with 2.3.0

### ISSUE THREAD

**Issue by MPrevail** [Atmosphere/atmosphere#1895]
Look at example https://github.com/Atmosphere/atmosphere-samples/tree/master/extensions-samples/guice/chat-guice

I get next error on deploy (mvn jetty:run)

```
Mar 13, 2015 11:13:39 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
Mar 13, 2015 11:13:39 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
  class org.atmosphere.jersey.AtmosphereResourceConfigurator
Mar 13, 2015 11:13:40 AM com.sun.jersey.spi.inject.Errors processErrorMessages
SEVERE: The following errors and warnings have been detected with resource and/or provider classes:
  SEVERE: The class org.atmosphere.samples.guice.ResourceChat does not have a public constructor and cannot be instantiated.
11:13:40.234 [main] ERROR o.atmosphere.cpr.AtmosphereFramework - Failed to initialize Atmosphere Framework
com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
	at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.19.jar:1.19]
	at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.19.jar:1.19]
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795) ~[jersey-server-1.19.jar:1.19]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790) ~[jersey-server-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509) ~[jersey-servlet-1.19.jar:1.19]
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339) ~[jersey-servlet-1.19.jar:1.19]
```

One of problem which I found:
```
ava.lang.NoSuchMethodException: org.atmosphere.guice.AtmosphereGuiceServlet$GuiceAtmosphereFramework.<init>(java.lang.Boolean, java.lang.Boolean)
```

I get this exception in  **AtmosphereFrameworkInitializer.class**  in method  
```
    protected AtmosphereFramework newAtmosphereFramework(Class<? extends AtmosphereFramework> frameworkClass) {
        AtmosphereFramework framework;
        try {
            framework = (AtmosphereFramework) frameworkClass.getDeclaredConstructor(
                    new Class[]{Boolean.class,Boolean.class}).newInstance(false, false);
        } catch (Exception e) {
            framework = new AtmosphereFramework(false, false);
        }

        return framework;
    }
```
You try create instance of inner class AtmosphereGuiceServlet$GuiceAtmosphereFramework which impossible. This class should be static. Make GuiceAtmosphereFramework as static fix this exception and Inject start worked. But incorrect anyway.

**Comment by jfarcand** [comment]
Fixed https://github.com/Atmosphere/atmosphere/commit/3eeed40b05cdf9c804056ac246500a56f7d43bd0

**Comment by jfarcand** [comment]
@MPrevail Great work! Fixed by now.
