### ISSUE TITLE
Unable to load atmosphere-runtime and atmosphere-annotations into OSGi (Apache Karaf)

### ISSUE THREAD

**Issue by sakno** [Atmosphere/atmosphere#1896]
The following error occurs when I try to install atmosphere-runtime and atmosphere-annotations as OSGi bundles into Apache Karaf:
```
java.lang.Exception: Could not start bundle mvn:org.atmosphere/atmosphere-annotations/2.2.6 in feature(s) http-adapter-feature-1.0.0: Uses constraint violation. Unable to resolve bundle revision org.atmosphere.annotations [129.0] because it exports package 'org.atmosphere.annotation' and is also exposed to it from bundle revision org.atmosphere.runtime [130.0] via the following dependency chain:

  org.atmosphere.annotations [129.0]
    import: (&(osgi.wiring.package=org.atmosphere.config.service)(version>=2.2.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=org.atmosphere.config.service; uses:=org.atmosphere.annotation
    export: osgi.wiring.package=org.atmosphere.annotation
  org.atmosphere.runtime [130.0]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:480)
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:435)
	at org.apache.karaf.features.internal.BootFeaturesInstaller.installBootFeatures(BootFeaturesInstaller.java:92)
	at org.apache.karaf.features.internal.BootFeaturesInstaller.start(BootFeaturesInstaller.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_75]
	at org.apache.aries.blueprint.utils.ReflectionUtils.invoke(ReflectionUtils.java:297)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.invoke(BeanRecipe.java:958)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.runBeanProcInit(BeanRecipe.java:712)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:824)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:787)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[15:org.apache.aries.blueprint.core:1.4.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_75]
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:681)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:378)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:269)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:276)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:245)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:235)[15:org.apache.aries.blueprint.core:1.4.1]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463)[9:org.apache.aries.util:1.1.0]
	at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422)[9:org.apache.aries.util:1.1.0]
	at org.apache.felix.framework.util.SecureAction.invokeBundleEventHook(SecureAction.java:1103)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.createWhitelistFromHooks(EventDispatcher.java:695)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:483)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4403)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2092)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1291)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)[org.apache.felix.framework-4.2.1.jar:]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_75]
Caused by: org.osgi.framework.BundleException: Uses constraint violation. Unable to resolve bundle revision org.atmosphere.annotations [129.0] because it exports package 'org.atmosphere.annotation' and is also exposed to it from bundle revision org.atmosphere.runtime [130.0] via the following dependency chain:

  org.atmosphere.annotations [129.0]
    import: (&(osgi.wiring.package=org.atmosphere.config.service)(version>=2.2.0)(!(version>=3.0.0)))
     |
    export: osgi.wiring.package=org.atmosphere.config.service; uses:=org.atmosphere.annotation
    export: osgi.wiring.package=org.atmosphere.annotation
  org.atmosphere.runtime [130.0]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)[org.apache.felix.framework-4.2.1.jar:]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:942)
	at org.apache.karaf.features.internal.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:477)
``` 
I think that this happen because both bundles export the same package (org.atmosphere.annotation).

Atmoshere Framework version: 2.2.6
Apache Karaf version: 3.0.2

**Comment by sakno** [comment]
I see that atmosphere-annotations.jar and atmosphere-runtime.jar exports org.atmosphere.annotation package with overlapped classes (for example, WebSocketProtocolServiceProcessor). Of course, this kind of packaging is not allowed for OSGi environment, because two bundles exports the same class with the same package name.

How can I use Atmosphere Framework with Jersey in OSGi environment? Is there any alternative set of dependencies?

**Comment by sakno** [comment]
I've found a workaround that consists of 2 steps.

The first, you should change dependency scope from `provided` to `compile`:
```xml
<dependency>
            <groupId>org.atmosphere</groupId>
            <artifactId>atmosphere-jersey</artifactId>
            <version>2.2.6</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.atmosphere</groupId>
            <artifactId>atmosphere-annotations</artifactId>
            <version>2.2.6</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.atmosphere</groupId>
            <artifactId>atmosphere-runtime</artifactId>
            <version>2.2.6</version>
            <scope>compile</scope>
        </dependency>
```

The second, you should embed Atmosphere dependencies into the OSGi bundle that containts implementation of REST service:
```xml
<plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>your-symbolic-name</Bundle-SymbolicName>
                        <Bundle-Activator>ActivatorClass</Bundle-Activator>
                        <Import-Package>
                            !org.eclipse.jetty.websocket.*,
                            !org.atmosphere.jboss.*,
                            !org.apache.tomcat.*,
                            !javax.websocket.*,
                            !com.sun.grizzly*,
                            !com.sun.enterprise.*,
                            !weblogic.*,
                            !org.apache.catalina.*,
                            !org.apache.coyote.*,
                            !org.apache.shiro.*,
                            !org.glassfish.*,
                            !org.jboss.*,
                            !org.mortbay.*,
                            *
                        </Import-Package>
                        <Embed-Dependency>*;scope=compile</Embed-Dependency>
                    </instructions>
                </configuration>
            </plugin>
```
This is just a workaround, not a solution for production environment. In normal situation, `atmosphere-annotations.jar` should not duplicate classes from `atmosphere-runtime.jar`.

**Comment by jfarcand** [comment]
@sakno Good catch. That's a really long standing issue. I will fix it by renaming atmosphere-runtime/org.atmosphere.annotations => atmosphere-runtime/org.atmosphere.cpr.annotations. That should fix your issue.

**Comment by sakno** [comment]
In what version the issue will be fixed?

**Comment by jfarcand** [comment]
@sakno will fix push it in 2.3.0 and once I have the OK from yo it works, will backport it.

**Comment by jfarcand** [comment]
OK I've decided to not export atmosphere-runtime's  `org.atmosphere.annotations` because those classes are internal, except for one class `Processor`. I will move that class out of that package but first can you try `2.3.0-SNAPSHOT`

**Comment by jfarcand** [comment]
@sakno Does the fixes works?

**Comment by sakno** [comment]
Yep. Thanks.

**Comment by hieplq** [comment]
> OK I've decided to not export atmosphere-runtime's org.atmosphere.annotations

i deploy atmosphere-runtime on equinox and jetty 9.4.12. i get bellow exception
in case i add "export package org.atmosphere.annotations" to atmosphere-runtime, it can resolve issue

`09:53:45.381-----------> ServletContainerInitializersStarter.warn:  [21]
java.lang.ClassNotFoundException: org.atmosphere.annotation.BroadcasterCacheServiceProcessor cannot be found by org.adempiere.ui.zk_6.1.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at org.eclipse.jetty.osgi.boot.internal.webapp.OSGiWebappClassLoader.loadClass(OSGiWebappClassLoader.java:104)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:65)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:130)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:355)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:505)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
`
