### ISSUE TITLE
Can't use Atmosphere Framework with Jersey in Apache Karaf

### ISSUE THREAD

**Issue by sakno** [Atmosphere/atmosphere#1899]
May be this issue exist due to lack of atmosphere+jersey+osgi example, but this conbination has no obvious solution, really.

So, my first attemption was finished with #1896 issue. OK, I've found the workaround for this problem. In the second attemption I was trying to connect to my Jersey-based Atmosphere-enabled service and take look at this:
```
javax.ws.rs.WebApplicationException: java.lang.IllegalStateException: The Atmosphere Framework is not installed properly and unexpected result may occurs.
	at org.atmosphere.jersey.AtmosphereFilter$Filter.filter(AtmosphereFilter.java:218)[133:http:1.0.0]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1489)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)[132:com.sun.jersey.servlet:1.18.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[41:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:77)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_75]
```
My service is implemented on top of Jersey 1.18.1. The service class looks like this:
```
@Path("/")
@Singleton
@org.atmosphere.config.service.Singleton
public final class RestService {
@GET
    @Path("/notifications/{" + RESOURCE_NAME_PARAM + "}")
    @Suspend(contentType = MediaType.APPLICATION_JSON)
    public SuspendResponse<String> subscribe(@PathParam(RESOURCE_NAME_PARAM) final String resourceName) throws WebApplicationException{
        final Broadcaster broadcaster = notifications.getBroadcaster(resourceName);
        if(broadcaster != null)
            return new SuspendResponse.SuspendResponseBuilder<String>()
                .broadcaster(broadcaster)
                .build();
        else throw new WebApplicationException(new IllegalArgumentException(String.format("Unknown resource %s", resourceName)), Response.Status.NOT_FOUND);
    }
}
```
`notifications` is my internal collection of broadcasters. My OSGi bundle expose this service using `HttpService` OSGi service, i.e. via HTTP server provided by Apache Karaf:
```java
publisher.registerServlet("/my-context", new HttpAdapterServlet(attributes, notifications), null, null);
//publisher is a reference to org.osgi.service.http.HttpService
```
`HttpAdapterServlet` is a servlet instance configured programmatically:
```java
import com.sun.jersey.api.core.DefaultResourceConfig;
import com.sun.jersey.api.core.ResourceConfig;
import com.sun.jersey.spi.container.servlet.ServletContainer;
import javax.ws.rs.core.Application;

final class HttpAdapterServlet extends ServletContainer {
    private static final long serialVersionUID = -4507714971473917629L;

    private static Application createResourceConfig(final RestService serviceInstance){
        final ResourceConfig result = new DefaultResourceConfig();
        result.getSingletons().add(serviceInstance);
        return result;
    }

    HttpAdapterServlet(){
        super(createResourceConfig(new RestService()));
    }
```
The exception described above produce by the following portion of code (inside of Atmosphere):
```java
//AtmosphereFilter.java:214
            AtmosphereConfig config = (AtmosphereConfig) servletReq.getAttribute(ATMOSPHERE_CONFIG);
            if (config == null) {
                logger.error(INSTALLATION_ERROR);
                throw new WebApplicationException(new IllegalStateException(INSTALLATION_ERROR));
            }
```
I see that `HttpServletRequest` doesn't have `ATMOSPHERE_CONFIG` property. So, my question is _how to configure Atmosphere Framework for Jersey/OSGi_?

Possibly, I should add some code into `HttpAdapterServlet` implementation but I don't known what. 

Apache Karaf 3.2.1
Jersey 1.18.1
Atmosphere Framework 2.2.6

P.S.: My REST service is configured programmatically and I don't have `web.xml`.
P.P.S: Any other operations in `RestService` working normally

**Comment by sakno** [comment]
I tried to configure `AtmosphereFramework` manually but without success. My Servlet definition:
```java
final class HttpAdapterServlet extends ServletContainer {
    private static final long serialVersionUID = -4507714971473917629L;

    private static Application createResourceConfig(final AdapterRestService serviceInstance){
        final ResourceConfig result = new DefaultResourceConfig();
        result.getSingletons().add(serviceInstance);
        return result;
    }

    private final AtmosphereFrameworkInitializer frameworkInitializer;

    HttpAdapterServlet(){
        super(createResourceConfig(new AdapterRestService()));
        frameworkInitializer = new AtmosphereFrameworkInitializer(false, true);
    }

    @Override
    public void init(final ServletConfig config) throws ServletException {
        frameworkInitializer.configureFramework(config);
        super.init(config);
    }

    @Override
    public void destroy() {
        super.destroy();
        frameworkInitializer.destroy();
    }
}
```
The result is 
```
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)[130:com.sun.jersey.core:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)[131:com.sun.jersey.jersey-server:1.18.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:491)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:321)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:376)[132:com.sun.jersey.servlet:1.18.1]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:559)[132:com.sun.jersey.servlet:1.18.1]
	at javax.servlet.GenericServlet.init(GenericServlet.java:161)[41:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
	at org.atmosphere.util.AtmosphereFilterChain.init(AtmosphereFilterChain.java:89)[133:http:1.0.0]
	at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWrapper.init(ReflectorServletProcessor.java:297)[133:http:1.0.0]
	at org.atmosphere.handler.ReflectorServletProcessor.init(ReflectorServletProcessor.java:176)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereFramework.initAtmosphereHandler(AtmosphereFramework.java:1573)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:891)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:780)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:68)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:89)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:85)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:80)[133:http:1.0.0]
	at http.HttpAdapterServlet.init(HttpAdapterServlet.java:36)[133:http:1.0.0]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doStart(HttpServiceContext.java:222)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$1.start(JettyServerImpl.java:202)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:215)[55:org.ops4j.pax.web.pax-web-runtime:3.1.2]
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:189)[55:org.ops4j.pax.web.pax-web-runtime:3.1.2]
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:174)[55:org.ops4j.pax.web.pax-web-runtime:3.1.2]
	at org.ops4j.pax.web.service.internal.HttpServiceProxy.registerServlet(HttpServiceProxy.java:64)[55:org.ops4j.pax.web.pax-web-runtime:3.1.2]
```

**Comment by sakno** [comment]
The next attemption is to configure `AtmosphereServlet` programmatically as it is described in your example [here]() produces NPE:
```
java.lang.NullPointerException
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2076)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:198)[133:http:1.0.0]
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:184)[133:http:1.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)[41:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[41:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:77)[56:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[47:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_75]
```
Programmatic configuration consits of the `AtmosphereServlet` instantiation and specifying `com.sun.jersey.config.property.packages` init parameter:
```java
final AtmosphereFramework framework = new AtmosphereFramework();
framework.addInitParameter("com.sun.jersey.config.property.packages", "http"); //http is my testing package
```

**Comment by sakno** [comment]
Atmosphere + Jersey + OSGi + programmatic configuration is possible!

So, my preconditions:

1. I have a programmatically configured Servlet as [ServletContainer](https://jersey.java.net/apidocs/1.18/jersey/com/sun/jersey/spi/container/servlet/ServletContainer.html) from Jersey. This is necessary for me because my singleton REST service has custom instantiation logic and custom constructor that cannot be automated via DI
1. My REST service contains normal REST operations with `@GET` and `@POST` annotations which should be handled by default Jersey Servlet
1. The same REST service contains Atmosphere-enabled operations used to publish message to the outside world. Requests for such methods should be handled by `AtmosphereServlet`

The solution combines customly instantiated `ServletContainer` with `AtmosphereServlet`. This is the non-obvious solution due of the lack of examples. This is a really challenge for me.

It is consists of the following steps
1. Write your own ServletFactory
1. Customize `AtmosphereServlet`, `AtmosphereFramework` and `AtmosphereFrameworkInitializer`
1. Instantiate customized `AtmosphereServlet` and register it via `HttpService` service.

Let's begin:
The first, we should introduce a new class called `ServletFactory` that is used to instantiate `ServletContainer`:
```java
public final class ServletFactory{
       private final MyParamClass param1;

       public ServletFactory(final MyParamClass p){
          this.param1 = p;
       }

       private static Application createResourceConfig(final RestService serviceInstance){
            final DefaultResourceConfig result = new DefaultResourceConfig();
            result.getSingletons().add(serviceInstance);
            return result;
        }

        @Override
        public ServletContainer get() {
            return new ServletContainer(createResourceConfig(new RestService(param1)));
        }
}
```
The second, customize `AtmosphereServlet`, `AtmosphereFramework` and `AtmosphereFrameworkInitializer`:
```java
final class AtmosphereServletBridge extends AtmosphereServlet {
    private static final long serialVersionUID = 1446026354420742643L;

    private static final class AtmosphereFrameworkBridge extends AtmosphereFramework{
        private final ServletFactory servletFactory;

        private AtmosphereFrameworkBridge(final ServletFactory servletFactory) {
            super(false, true);
            this.servletFactory = servletFactory;
        }

        @Override
        public <T, U extends T> T newClassInstance(final Class<T> classType, final Class<U> defaultType) throws InstantiationException, IllegalAccessException {
            return classType == Servlet.class ?
                    classType.cast(servletFactory.get()) :
                    super.newClassInstance(classType, defaultType);
        }
    }

    private static final class AtmosphereFrameworkInitializerBridge extends AtmosphereFrameworkInitializer{
        private final ServletFactory servletFactory;

        private AtmosphereFrameworkInitializerBridge(final ServletFactory servletFactory){
            super(false, true);
            this.servletFactory = servletFactory;
        }

        @Override
        protected AtmosphereFrameworkBridge newAtmosphereFramework() {
            return new AtmosphereFrameworkBridge(servletFactory);
        }
    }

    private final AtmosphereFrameworkInitializerBridge customizedInitializer;

    AtmosphereServletBridge(final ServletFactory servletFactory){
        super(false, true);
        customizedInitializer = new AtmosphereFrameworkInitializerBridge(servletFactory);
    }

    @Override
    protected AtmosphereServlet configureFramework(final ServletConfig sc, final boolean init) throws ServletException {
        customizedInitializer.configureFramework(sc, init, false);
        framework = customizedInitializer.framework();
        return this;
    }

    @Override
    protected AtmosphereFrameworkBridge newAtmosphereFramework() {
        final AtmosphereFrameworkBridge result = customizedInitializer.newAtmosphereFramework();
        framework = result;
        return result;
    }

    @Override
    public AtmosphereFramework framework() {
        return framework;
    }

    @Override
    public void destroy() {
        try {
            customizedInitializer.destroy();
        }
        finally {
            framework = null;
        }
    }
}
```
The third, instantiate `AtmosphereServletBridge` and register it via `HttpService`:
```java
HttpService publisher = ...;
ServletFactory = new ServletFactory(p1);
publisher.registerServlet("/context", new AtmosphereServletBridge(servletFactory), null, null);
```

**Summary**: This approach provides the following benefits:
1. It is possible to configure Atmosphere Framework for **any** servlet-based application in **any** OSGi environment which supports `org.osgi.service.http.HttpService` (this service is a part of OSGi Enterprise specification)
1. There is no servlet container lock. This solution can be used on any servlet container (because Jersey can be executed on top of any Servlet-compliant container)
1. The solution describes the most generic case with fully programmatic setup in OSGi without `web.xml`

Of course, this solution may be improved (using `AtmosphereObjectFactory` instead of overridding [newClassInstance](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L2928).

**Comment by jfarcand** [comment]
@sakno Great work.!!! If you want, do a pull request against the `atmosphere-jersey` and I will integrate it, with a special `AtmosphereObjectFactory` that can return a new `ServletContainer` when not specified, so your implementation works in the normal case as well.

**Comment by sakno** [comment]
Unfortunatly, this solution requires full integration testing environment including Apache Karaf as a container for integration tests. Just look at this hell:
```xml
<dependency>
            <groupId>org.apache.karaf</groupId>
            <artifactId>apache-karaf</artifactId>
            <version>${karaf.version}</version>
            <scope>test</scope>
            <type>tar.gz</type>
            <exclusions>
                <exclusion>
                    <artifactId>org.apache.karaf.client</artifactId>
                    <groupId>org.apache.karaf</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.eclipse</groupId>
                    <artifactId>org.eclipse.osgi</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.gogo.runtime</artifactId>
            <version>${felix.gogo.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-inject</artifactId>
            <version>${exam.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-invoker-junit</artifactId>
            <version>${exam.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-container-karaf</artifactId>
            <version>${exam.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-junit4</artifactId>
            <version>${exam.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
Also, it is necessary to create domain-specific testing framework for Atmosphere on top of Pax Exam for Karaf Container, because pure Pax Exam is very difficult to use. I have this hand-written testing framework on top of Pax Exam but it is very specific for my project and not reusable.
But I can help you with `AtmosphereObjectFactory` by writting very convenient _builder_ for this interface

**Comment by jfarcand** [comment]
@sakno OK but your solution is quite good just to re-use an existing `ServletContainer` so I do think we should add your code, and at least people will have a start and can do the complicated stuff by reading this issue. What do you think?

**Comment by sakno** [comment]
@jfarcand The solution is not restricted to `ServletContainer` from Jersey. It can be used to integrate with any servlet class which implements `Servlet` interface from `javax` package. But at the beginning I wish to simplify `AtmosphereObjectFactory` customization. Then, I try to write a complete standalone example that demonstrates the solution shown above.

**Comment by harshild** [comment]
It would have been a great help if we had an official documentation or a working sample for this !
