### ISSUE TITLE
Prevent Duplicate AtmosphereInterceptor to be installed

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1905]
#1877 exposed a problem where `AtmosphereInterceptor` can be added more than once, causing all kind of issues: 

#1890 
#1845

**Comment by gdrouet** [comment]
From #1877: the issue still exists for meta service installation. We should create a unit test for it. I can fix it this week if you're ok.

**Comment by jfarcand** [comment]
@gdrouet OK thanks. I will cut `2.3.0-RC5` once done. Thanks!!

**Comment by jfarcand** [comment]
@gdrouet Seems there is a regression with the unit test
```java
"main" prio=5 tid=0x00007ff03980b000 nid=0x1303 waiting on condition [0x0000000107b5f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000762411c70> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
	at org.atmosphere.cpr.AtmosphereResourceTest.testCancelParentUUID(AtmosphereResourceTest.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:580)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:478)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:617)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:885)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:110)
	at org.testng.TestRunner.runWorkers(TestRunner.java:712)
	at org.testng.TestRunner.privateRun(TestRunner.java:582)
	at org.testng.TestRunner.run(TestRunner.java:477)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:324)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:319)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:292)
	at org.testng.SuiteRunner.run(SuiteRunner.java:198)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:821)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:788)
	at org.testng.TestNG.run(TestNG.java:708)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
"VM Thread" prio=5 tid=0x00007ff039857000 nid=0x3103 runnable
```
The test wait/hangs on OS X/Mavericks & JDK 7. Are those tests passing for you?

**Comment by gdrouet** [comment]
Grrr I knew I should run all the tests before I push. Is it better now? Also make sure you agree with the commit fe656120bddc9d8b3267a5e43a40bf2e9d6d5733 (I was not able to run mvn clean install without that but did not really dig).

**Comment by jfarcand** [comment]
@gdrouet The build is completely broken right now and I can't work on it before tonight. So I've commented out your code for now so at least it doesn't hangs :-)

**Comment by gdrouet** [comment]
@jfarcand even if with commit 3defc6011124b786c1d2fa827b93365233d36a70? All tests are now passing for me.
