### ISSUE TITLE
[Tyrus] Tyrus/GlassFish 4.1 fails to initialize jsr356

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1946]
```java
[#|2015-04-17T08:59:01.511-0400|SEVERE|glassfish 4.1|javax.enterprise.web.core|_ThreadID=54;_ThreadName=AutoDeployer;_TimeMillis=1429275541511;_LevelValue=1000;_MessageID=AS-WEB-CORE-00108;|
  ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: java.lang.IllegalStateException: ServerContainer is null. Make sure you are using 1.7+ and your server has websocket support enabled
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5954)
	at com.sun.enterprise.web.WebModule.start(WebModule.java:691)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2286)
	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1932)
	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:164)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:597)
	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:484)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:412)
	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:403)
	at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:233)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.catalina.LifecycleException: java.lang.IllegalStateException: ServerContainer is null. Make sure you are using 1.7+ and your server has websocket support enabled
	at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:6037)
	at com.sun.enterprise.web.WebModule.callServletContainerInitializers(WebModule.java:774)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5929)
	... 34 more
Caused by: java.lang.IllegalStateException: ServerContainer is null. Make sure you are using 1.7+ and your server has websocket support enabled
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:53)
	at org.atmosphere.cpr.ContainerInitializer.onStartup(ContainerInitializer.java:73)
	at org.apache.catalina.core.StandardContext.callServletContainerInitializers(StandardContext.java:6031)
	... 36 more
|#]
```

**Comment by jfarcand** [comment]
Works fine with 4.0.0

**Comment by jfarcand** [comment]
@pavelbucek nevermind...seems Tyrus/GlassFish is the only implementation failing with 
```java
Caused by: java.lang.IllegalStateException: Not in 'deploy' scope.
	at org.glassfish.tyrus.servlet.TyrusServletServerContainer.addEndpoint(TyrusServletServerContainer.java:83) ~[tyrus-container-servlet.jar:na]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:76) ~[atmosphere-runtime-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40) ~[atmosphere-runtime-2.3.0-SNAPSHOT.jar:2.3.0-SNAPSHOT]
```
There was a regression in Atmosphere's master when handling that case.

**Comment by pavelbucek** [comment]
Hm, that's unfortunate. I guess we could soften that check - make it configurable - would that help? (I'm asking to get the severity of this issue for atmosphere).

**Comment by jfarcand** [comment]
@pavelbucek Yes that would be a good idea, but this is now fixed in Atmosphere (was really a regression from my side in 2.3). Now it seems WebLogic 12.1.3.0 suffer a similar issue but it may be a regression in 2.3 as well. Investigating :-)
