### ISSUE TITLE
Invalid lookup class org.atmosphere.plugin.hazelcast.HazelcastBroadcaster. Cached class is: org.atmosphere.cpr.DefaultBroadcaster

### ISSUE THREAD

**Issue by uberstud87** [Atmosphere/atmosphere#1981]
I'm still experiencing the issue listed in https://github.com/Atmosphere/atmosphere/issues/1953.

I'm running on a JBoss EAP 6.3.3 with the following Atmosphere dependencies. I have excluded `atmosphere-compat-jbossweb` from my `atmosphere-runtime-native`.

I noticed that `hazelcast-3.3.jar` is pulled into the project instead of the `hazelcast-all-3.4.1.jar` in https://github.com/Atmosphere/atmosphere/issues/1953, probably due to the different versions. Thus, my versions as follows:

Atmosphere | Version
------------ | -------------
atmosphere-runtime-native | 2.3.1
atmosphere-hazelcast | 2.3.0 
atmosphere-javascript | 2.2.11

It was working fine with the previous version as follows:

Atmosphere | Version
------------ | -------------
atmosphere-runtime-native | 2.2.7
atmosphere-hazelcast | 2.2.1
atmosphere-javascript | 2.2.11

I apologize for the wall of text below:
> 17:54:53,788 WARN  [org.atmosphere.config.managed.ManagedServiceInterceptor] (http-/127.0.0.1:8080-1) Unable to create AtmosphereHandler: java.lang.RuntimeException: java.lang.IllegalStateException: Invalid lookup class org.atmosphere.plugin.hazelcast.HazelcastBroadcaster. Cached class is: org.atmosphere.cpr.DefaultBroadcaster
	at org.atmosphere.cpr.AtmosphereFramework$AtmosphereHandlerWrapper.<init>(AtmosphereFramework.java:307) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AtmosphereFramework.createWrapperAndConfigureHandler(AtmosphereFramework.java:643) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AtmosphereFramework.addAtmosphereHandler(AtmosphereFramework.java:602) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.config.managed.ManagedServiceInterceptor.mapAnnotatedService(ManagedServiceInterceptor.java:65) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.config.managed.ServiceInterceptor.mapAnnotatedService(ServiceInterceptor.java:96) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.config.managed.ServiceInterceptor.inspect(ServiceInterceptor.java:45) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:313) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:174) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:108) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.container.JBossWebCometSupport.service(JBossWebCometSupport.java:91) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2257) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AtmosphereServlet.event(AtmosphereServlet.java:326) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilterEvent(ApplicationFilterChain.java:458) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilterEvent(ApplicationFilterChain.java:364) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:229) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
	at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
	at org.jboss.as.web.session.ClusteredSessionValve.handleRequest(ClusteredSessionValve.java:134) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.jboss.as.web.session.ClusteredSessionValve.invoke(ClusteredSessionValve.java:99) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.jboss.as.web.session.JvmRouteValve.invoke(JvmRouteValve.java:92) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.jboss.as.web.session.LockingValve.invoke(LockingValve.java:64) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.4.3.Final-redhat-2.jar:7.4.3.Final-redhat-2]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:876) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:607) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2056) [jbossweb-7.4.10.Final-redhat-1.jar:7.4.10.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: java.lang.IllegalStateException: Invalid lookup class org.atmosphere.plugin.hazelcast.HazelcastBroadcaster. Cached class is: org.atmosphere.cpr.DefaultBroadcaster
	at org.atmosphere.cpr.DefaultBroadcasterFactory.lookup(DefaultBroadcasterFactory.java:213) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.DefaultBroadcasterFactory.lookup(DefaultBroadcasterFactory.java:198) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.DefaultBroadcasterFactory.lookup(DefaultBroadcasterFactory.java:193) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	at org.atmosphere.cpr.AtmosphereFramework$AtmosphereHandlerWrapper.<init>(AtmosphereFramework.java:302) [atmosphere-runtime-native-2.3.1.jar:2.3.1]
	... 30 more

Do let me know what else to provide in order to assist with the debugging.

**Comment by jfarcand** [comment]
@uberstud87 Please provide a test case or a .war reproducing the issue.

**Comment by uberstud87** [comment]
@jfarcand I have uploaded a test case at http://www.filedropper.com/atmosphere
I have also emailed you a copy. 

Do let me know if this is an issue or is there something wrong with my way of implementation.

**Comment by jfarcand** [comment]
@uberstud87 Thanks for the test!!!

**Comment by jfarcand** [comment]
@uberstud87  Ealy next week, my master!!

**Comment by uberstud87** [comment]
My lord... I'm waiting for you!  


     On Friday, 29 May 2015, 23:15, Jeanfrancois Arcand <notifications@github.com> wrote:
   

 @uberstud87 Ealy next week, my master!!—

**Comment by jfarcand** [comment]
Have you looked at the mailing list ;-) 2.3.2 has been release ;-)

**Comment by uberstud87** [comment]
3 cheers for Jeanfrancois!  


     On Tuesday, 9 June 2015, 23:24, Jeanfrancois Arcand <notifications@github.com> wrote:
   

 Have you looked at the mailing list ;-) 2.3.2 has been release ;-)—
