### ISSUE TITLE
Using IE9, NoSuchMethodError displayed in log file.

### ISSUE THREAD

**Issue by elfwine** [Atmosphere/atmosphere#1982]
Used latest atmosphere build, adopted the sse-chat sample, when testing in IE8 and IE9, the error below appeared in the log file. In other browsers like Chrome and Firefox or even IE10, these errors do not occur. Though the broadcast messages successfully delivered to IE8 and IE9 browsers, error log is not good to see by client. I tried a CORSInceptor implementation but still the error didn't disappear. Looking for other options to fix this. Thanks.

java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeader(Ljava/lang/String;)Ljava/lang/String;
	at org.atmosphere.cpr.AtmosphereResponse.getHeader(AtmosphereResponse.java:416)
	at org.atmosphere.interceptor.CorsInterceptor.inspect(CorsInterceptor.java:57)
	at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:313)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:174)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:108)
	at org.atmosphere.container.BlockingIOCometSupport.service(BlockingIOCometSupport.java:63)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2257)
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:199)
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:662)

**Comment by jfarcand** [comment]
Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1. You have multiple servlet.jar in your classpath
