### ISSUE TITLE
ConcurrentModificationException in WebSocket.shiftAttributes method

### ISSUE THREAD

**Issue by timofeevda** [Atmosphere/atmosphere#2021]
We've got following exception using Tomcat 8 + Atmosphere 2.3.1 with JSR356Endpoint. Exception occurs randomly and, I guess, is related to #1908.
```java
E 150713 143434.875 [catalina-exec-33] JSR356Endpoint - 
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at java.util.HashMap.putMapEntries(HashMap.java:511)
        at java.util.HashMap.putAll(HashMap.java:784)
        at org.atmosphere.websocket.WebSocket.shiftAttributes(WebSocket.java:127)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:267)
        at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:222)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:138)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:696)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```
 Fixes made in #1908 still lack correct synchronization in **localAttributes** method of **AtmosphereRequestImpl** class.

I think the right way to fix this is to implement the same way of map copying as it's done in **shiftAttributes** of **WebSocket** class. Additional synchronization on map copying allows to avoid ConcurrentModification exception. Also ConcurrentHashMap can be used instead of Collections.synchronizedMap, but I'm not sure if weaker consistency is feasible in this place. So, **AtmosphereResourceImpl.localAttributes** method will look like:
```java
 @Override
    public Map<String, Object> localAttributes() {
        Map<String, Object> m = new HashMap<String, Object>();
        synchronized (b.localAttributes) {
            m.putAll(b.localAttributes);
        }
        return m;
    }
```
The same should be done to **AtmosphereResourceImpl.attributes** method cause it uses the same way to return **localAttributes** map

**WebSocket.shifAttributes** will be simplified to:
```java
public WebSocket shiftAttributes() {        
        attributesAtWebSocketOpen = Collections.unmodifiableMap(AtmosphereResourceImpl.class.cast(r).getRequest(false).localAttributes());
        return this;
    }
```

Also creating map copy in AtmosphereResponseImpl restricts users to use right setters/getters instead of direct access to underlying map.

**Comment by jfarcand** [comment]
I like it. Can you make a pull request with your recommendations? I will cut a release just for you if you do me that favor :-)

**Comment by timofeevda** [comment]
I've taken a look into this one more time and it seems to me that the fix with the least overhead is to make **localAttributes** map as a ConcurrentHashMap. This is because **localAttributes** map is used directly via **request.localAttributes().put** and **request.localAttributes().remove** invocations (require additional methods in Atmosphere requests to hide access to localAttributes map). I think in this case ConcurrentHashMap provides the same guaranties: synchronization for put/get requests and snapshots in case of getting attributes set before the websocket connection establishment. 

Actually I didn't make a pull request cause I'm not sure of preferable solution in this case, strong synchronization or less code with ConcurrentHashMap. If it's enough to have ConcurrentHashMap I'll make pull request or you can make changes yourself if you have time cause they are trivial.

**Comment by timofeevda** [comment]
I can make any of proposed changes in pull request. Please decide which is the most preferable one :)

**Comment by jfarcand** [comment]
ConcurrentHashMap is the best IMO. So go ahead (sorry for the delay, completely swamped those days). Thanks!!!

**Comment by timofeevda** [comment]
Didn't know a policy with forward/backporting so I created separate pull requests for branches and master, changes in master and 2.4.x are slightly different than in 2.3.x

**Comment by jfarcand** [comment]
@timofeevda Thanks!!!!!!!!!
