### ISSUE TITLE
incomingBroadcast Exception Broadcaster will be broken unless reconfigured

### ISSUE THREAD

**Issue by 785129039** [Atmosphere/atmosphere#2038]
2015-08-25 09:59:27 WARN  (org.atmosphere.util.AbstractBroadcasterProxy:77)- incomingBroadcast Exception. Broadcaster will be broken unless reconfigured
redis.clients.jedis.exceptions.JedisConnectionException: It seems like server has closed the connection.
	at redis.clients.util.RedisInputStream.readLine(RedisInputStream.java:91)
	at redis.clients.jedis.Protocol.processMultiBulkReply(Protocol.java:110)
	at redis.clients.jedis.Protocol.process(Protocol.java:63)
	at redis.clients.jedis.Protocol.read(Protocol.java:122)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:196)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:88)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:83)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:1974)
	at org.atmosphere.plugin.redis.RedisUtil.incomingBroadcast(RedisUtil.java:158)
	at org.atmosphere.plugin.redis.RedisBroadcaster.incomingBroadcast(RedisBroadcaster.java:93)
	at org.atmosphere.util.AbstractBroadcasterProxy$1.run(AbstractBroadcasterProxy.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.atmosphere.util.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at org.atmosphere.util.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at org.atmosphere.util.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:876)
	at org.atmosphere.util.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1705)
	at org.atmosphere.util.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1660)
	at org.atmosphere.util.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

but is not effect working

**Comment by 785129039** [comment]
my redis.window.config

![image](https://cloud.githubusercontent.com/assets/4322248/9457186/9498ba4c-4b12-11e5-8909-a623e92d43cd.png)

**Comment by jfarcand** [comment]
Please use the mailing list for question: https://groups.google.com/group/atmosphere-framework?pli=1
