### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by cnsgithub** [Atmosphere/atmosphere#2062]
Hi, this happened occasionally   (2.4.0 - RC5)

```java
12:09:25,643 ERROR [stderr] (default task-10) Exception in thread "default task-10" java.util.ConcurrentModificationException

12:09:25,643 ERROR [stderr] (default task-10) 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)

12:09:25,643 ERROR [stderr] (default task-10) 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)

12:09:25,643 ERROR [stderr] (default task-10) 	at io.undertow.servlet.util.IteratorEnumeration.nextElement(IteratorEnumeration.java:44)

12:09:25,643 ERROR [stderr] (default task-10) 	at org.atmosphere.cpr.AtmosphereRequestImpl.getAttributeNames(AtmosphereRequestImpl.java:846)

12:09:25,643 ERROR [stderr] (default task-10) 	at org.jboss.weld.context.beanstore.http.RequestBeanStore.getAttributeNames(RequestBeanStore.java:48)

12:09:25,643 ERROR [stderr] (default task-10) 	at org.jboss.weld.context.beanstore.AttributeBeanStore.getPrefixedAttributeNames(AttributeBeanStore.java:199)
```

**Comment by jfarcand** [comment]
@cnsgithub Thanks. How do you reproduce it? Using WebSocket or HTTP? Thanks

**Comment by cnsgithub** [comment]
HI, Unfortunately i cannot reproduce it, its random - Using websocket and long-polling as fallback. If i can reproduce in future it ill post how it can be done

**Comment by jfarcand** [comment]
@cnsgithub I just need to know which transport is in use and I will manage to fix it and reproduce it. Thanks!
