### ISSUE TITLE
Nested webapp context path breaks @ManagedResource

### ISSUE THREAD

**Issue by dparish** [Atmosphere/atmosphere#2064]
Given a ManagedResource path such as:
atmosphere/variable-pipeline/{tenantId}/{parentId}/{childId}

You would expect this path to work no matter what the webapp context is.  In fact if the webapp context is:

/foo
or
/bar
everything works

but if the webapp context is
/foo/bar/zed

You get a failure.  Here is what you see in the logs:

```
org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler maps request for /foo/bar/zed/atmosphere/variable-pipeline/0/0/0
	at org.atmosphere.cpr.AsynchronousProcessor.map(AsynchronousProcessor.java:366)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:161)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:108)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2262)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:566)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:220)
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:223)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:138)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:696)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

I can't tell for sure but I think the error is in JSR356Endpoint.java where it parses the path.
```
        String[] paths = uri.getPath() != null ? uri.getPath().split("/") : new String[]{};

        int pathInfoStartIndex = 3;
```

I'm not sure what the code is trying to do here exactly, but I think it should be comparing to the context path and not to an arbitrary split array index.

The customer for this project has some specific path requirements that relate to the SSO solution so we need to go with this nested webapp path.

**Comment by dparish** [comment]
I took a look at your master branch and noticed you had changed JSR345Endpoint.java. I changed my build to use 2.4.0-RC6 and everything worked. Oddly I had to add

compile('javax.inject:javax.inject:1')

Despite using Spring, but who cares it worked!!

Great job. Nothing's better than you squashing a bug before I even finished writing it up.

**Comment by jfarcand** [comment]
@dparish Thanks!!! Sorry for the trouble :-)
