### ISSUE TITLE
java.net.URISyntaxException: Expected hostname at index 5: ws://:0/

### ISSUE THREAD

**Issue by KY-7** [Atmosphere/atmosphere#2070]
Hi,
i'm trying to integrate the latest spring (4.2.2.RELEASE) and latest atmosphere(2.3.5) on tomcat 8.0.28.
I've used the "spring tiles" example as a startup code (which does not actually work).

Are those frameworks versions supposed to work together?

Here the error code which seems to be related to a bad URI:

(xyz is the pubsub topic i entered; spring-atmosphere is the application name)

java.lang.IllegalStateException: Could not get HttpServletRequest URI: Expected hostname at index 5: ws://:0/spring-atmosphere/pubsub/xyz?
	at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:162)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:215)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:109)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2275)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:566)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:220)
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:237)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:138)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:701)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
...

Thanks!

**Comment by jfarcand** [comment]
Please use the mailing list for question: https://groups.google.com/group/atmosphere-framework?pli=1
