### ISSUE TITLE
ConcurrentModificationException on request.getHeaderNames()

### ISSUE THREAD

**Issue by supertick** [Atmosphere/atmosphere#2072]
Hello Jeanfrancois,
Thanks for the amazing project ...

Perhaps I don't have things configured correctly.
I'm using nettosphere-assembly-2.3.0 with websockets and get the following error occasionally with request.getHeaderNames()

[New I/O worker #7] [ERROR] ------
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:894)
	at java.util.HashMap$KeyIterator.next(HashMap.java:928)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:333)
	at org.atmosphere.cpr.AtmosphereRequest.getAttributeNames(AtmosphereRequest.java:1047)
	at org.atmosphere.cpr.AtmosphereRequest.getHeaderNames(AtmosphereRequest.java:322)

naughty threads ?

Regards,
Greg.

**Comment by jfarcand** [comment]
Same as #2062
