### ISSUE TITLE
[Long-Polling] @PathParam not working

### ISSUE THREAD

**Issue by fanste** [Atmosphere/atmosphere#2080]
The injection of @PathParam is not working. The newly created AtmosphereHandler is only intercepted the first time but each successive invocation of that handler won't inject the parameters as the flag `wildcardMapping` is set to `false` on the newly created AtmosphereHandler.

To correct this you have to change the variable `path` to `targetPath` in the line 68 of [ManagedServiceInterceptor](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedServiceInterceptor.java#L68)

**Comment by fanste** [comment]
Submitted a [pull request](https://github.com/Atmosphere/atmosphere/pull/2081) for this issue.

As mentioned in the description of the pull request: The log will be spammed by a lot of messages of the type

```
18:19:22,302 INFO  [org.atmosphere.interceptor.HeartbeatInterceptor] (http-/0.0.0.0:8080-2) HeartbeatInterceptor configured withpaddingvalue'X',client frequency 60 seconds and server frequency 0 seconds
18:19:22,303 INFO  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-2) Installed AtmosphereInterceptor [CORS Interceptor Support, org.atmosphere.interceptor.IdleResourceInterceptor, TrackMessageSizeInterceptorusing|,UUIDTrackingInterceptor,DefaultResponse'sHeadersInterceptor,BrowserPaddingInterceptorSupport,AndroidInterceptorSupport,HeartbeatInterceptorSupport,SSEInterceptorSupport,JSONPInterceptorSupport,AtmosphereJavaScriptProtocol,org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor,Browserdisconnectiondetection,AtmosphereLifeCycle, @ManagedService Interceptor] mapped to AtmosphereHandler org.atmosphere.config.managed.ManagedAtmosphereHandler
```

I don't know if this is the expected behavior or if this is another bug anywhere in the handling of path parameters. If you remove the lines 68-70 you can't broadcast to that resource anymore.

**Comment by jfarcand** [comment]
What's the difference with this https://goo.gl/tyEh5D. This works as expected so I don't see where is yoru issue exactly.

**Comment by fanste** [comment]
Yes, the pull request uses more resource, thats why I said, that that can't be the desired behavior. But it was the only way to get it working. The root cause is the missing [localAttribute(PathParam.class.getName())](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedServiceInterceptor.java#L63) which is only available when that piece of code is executed per request. Maybe because the attribute is set on the request and not on the resource? I don't know the inner workings, sorry.

---

No, the example doesn't work as expected. I've opened 3 windows. Window 1 and 2 are connected to the room *test_room* with the users *user_A* and *user_B*. Window 3 is connected to room *test_house* with user *user_C*.

Below are the test results for the branches 2.4.x and master (3.0.0). All I did was to extend the log messages with the room name (e.g. ChatRoom.java line 125 `logger.info("{} just send {} to room {}", message.getAuthor(), message.getMessage(), chatroomName);`) and the `pom.xml` (native instead of normal runtime). The remaining code is the same as the example.

Please tell me what I did wrong as the code should work according to your statement.

---

Running 2.4.0-SNAPSHOT (using atmosphere-runtime-native has the same behavior)
![atmospherechatmultiroom_2 4 0-snapshot](https://cloud.githubusercontent.com/assets/3531183/10844361/3750b986-7eff-11e5-871d-475eb25ad961.png)
```
10:13:29,493 INFO  [org.jboss.web] (MSC service thread 1-8) JBAS018210: Registrierung von Webkontext: /atmosphere-chat-multiroom
10:13:29,640 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018565: Deployment "atmosphere-chat-multiroom.war" durch Deployment "atmosphere-chat-multiroom.war" ersetzt
10:13:50,569 ERROR [org.atmosphere.container.JBossWebCometSupport] (http-/0.0.0.0:8080-4) HttpEvent is null, JBoss APR Not Properly installed
10:13:50,570 WARN  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-4) Failed using comet support: org.atmosphere.container.JBossWebCometSupport, error: JBoss failed to detect this is a Comet application because the APR Connector is not enabled.Make sure atmosphere-compat-jboss.jar is not under your WEB-INF/lib and You must use the atmosphere-native-runtime dependency in order to use native Comet Supportthere is no context.xml under WEB-INF Is the NIO or APR Connector enabled?
10:13:50,571 ERROR [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-4) If you have more than one Connector enabled, make sure they both use the same protocol, e.g NIO/APR or HTTP for all. If not, org.atmosphere.container.BlockingIOCometSupport will be used and cannot be changed.
10:13:50,571 WARN  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-4) Using org.atmosphere.container.BlockingIOCometSupport
10:13:50,572 WARN  [org.atmosphere.cpr.AsynchronousProcessor] (http-/0.0.0.0:8080-4) Websocket protocol not supported
10:13:50,601 INFO  [org.atmosphere.interceptor.HeartbeatInterceptor] (http-/0.0.0.0:8080-4) HeartbeatInterceptor configured with padding value 'X', client frequency 60 seconds and server frequency 0 seconds
10:13:50,601 INFO  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-4) Installed AtmosphereInterceptor [CORS Interceptor Support,  Track Message Size Interceptor using |, UUID Tracking Interceptor, org.atmosphere.interceptor.IdleResourceInterceptor, Atmosphere LifeCycle, @ManagedService Interceptor, Default Response's Headers Interceptor, Browser Padding Interceptor Support, Android Interceptor Support, Heartbeat InterceptorSupport, SSE Interceptor Support, JSONP Interceptor Support, Atmosphere JavaScript Protocol, org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor, Browser disconnection detection] mapped to AtmosphereHandler org.atmosphere.config.managed.ManagedAtmosphereHandler
10:13:50,615 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) Browser 74d8aa95-c9e1-45f3-a59c-76a6b92b8284 connected to room null.
10:14:09,858 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-5) user_A just send hey to room null
10:14:25,180 WARN  [org.atmosphere.cpr.AsynchronousProcessor] (http-/0.0.0.0:8080-3) Websocket protocol not supported
10:14:25,273 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-3) Browser 9c7dec93-e1bc-47d3-b7bd-519f228850e1 connected to room null.
10:14:25,274 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-3)  just send  to room null
10:14:25,275 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-4)  just send  to room null
10:14:49,034 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-5) user_B just send hey to room null
10:15:08,539 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-5) Send message to room null
10:15:08,540 ERROR [org.atmosphere.config.managed.Invoker] (http-/0.0.0.0:8080-5) : java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_67]
        at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_67]
        at org.atmosphere.config.managed.Invoker.invokeMethod(Invoker.java:49) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.config.managed.ManagedAtmosphereHandler.message(ManagedAtmosphereHandler.java:367) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.config.managed.ManagedAtmosphereHandler.onRequest(ManagedAtmosphereHandler.java:171) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:223) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.container.BlockingIOCometSupport.service(BlockingIOCometSupport.java:63) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2281) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:190) [atmosphere-runtime-2.4.0-20151029.111850-59.jar:2.4.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.1.Final.jar:1.0.1.Final]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.1.Final.jar:1.0.1.Final]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:165) [jboss-as-web-7.1.3.Final.jar:7.1.3.Final]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:372) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:897) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:634) [jbossweb-7.0.17.Final-luk1.jar:]
        at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2039) [jbossweb-7.0.17.Final-luk1.jar:]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_67]
Caused by: java.lang.NullPointerException
        at org.atmosphere.samples.chat.ChatRoom.onPrivateMessage(ChatRoom.java:141) [classes:]
        ... 27 more

10:16:09,275 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-5) user_B just send test to room null
10:16:22,628 WARN  [org.atmosphere.cpr.AsynchronousProcessor] (http-/0.0.0.0:8080-5) Websocket protocol not supported
10:16:22,661 INFO  [org.atmosphere.interceptor.HeartbeatInterceptor] (http-/0.0.0.0:8080-5) HeartbeatInterceptor configured with padding value 'X', client frequency 60 seconds and server frequency 0 seconds
10:16:22,662 INFO  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-5) Installed AtmosphereInterceptor [CORS Interceptor Support,  Track Message Size Interceptor using |, UUID Tracking Interceptor, org.atmosphere.interceptor.IdleResourceInterceptor, Atmosphere LifeCycle, @ManagedService Interceptor, Default Response's Headers Interceptor, Browser Padding Interceptor Support, Android Interceptor Support, Heartbeat InterceptorSupport, SSE Interceptor Support, JSONP Interceptor Support, Atmosphere JavaScript Protocol, org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor, Browser disconnection detection] mapped to AtmosphereHandler org.atmosphere.config.managed.ManagedAtmosphereHandler
10:16:22,681 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-5) Browser 6495ef4c-111d-4b79-89a3-029f4fd96461 connected to room null.
10:16:22,685 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-12)  just send  to room null
10:16:22,686 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-13)  just send  to room null
10:16:28,072 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-1) user_C just send hey to room null
10:16:37,286 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-16) user_A just send  sent a message to all chatroom: C to A to room null
10:16:37,291 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-18) user_A just send  sent a message to all chatroom: C to A to room null
```

Running 3.0.0-SNAPSHOT (The output is from native this time)
![atmospherechatmultiroom_3 0 0-snapshot](https://cloud.githubusercontent.com/assets/3531183/10844367/41b9232c-7eff-11e5-99c0-607319426f8d.png)

```
12:03:11,827 INFO  [org.jboss.web] (MSC service thread 1-7) JBAS018210: Registrierung von Webkontext: /atmosphere-chat-multiroom
12:03:12,049 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) JBAS018565: Deployment "atmosphere-chat-multiroom.war" durch Deployment "atmosphere-chat-multiroom.war" ersetzt
12:03:17,253 WARN  [org.atmosphere.cpr.AsynchronousProcessor] (http-/0.0.0.0:8080-4) Websocket protocol not supported
12:03:17,275 INFO  [org.atmosphere.interceptor.HeartbeatInterceptor] (http-/0.0.0.0:8080-4) HeartbeatInterceptor configured with padding value 'X', client frequency 60 seconds and server frequency 0 seconds
12:03:17,276 INFO  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-4) Installed AtmosphereInterceptor [CORS Interceptor Support,  Track Message Size Interceptor using |, UUID Tracking Interceptor, org.atmosphere.interceptor.IdleResourceInterceptor, Atmosphere LifeCycle, @ManagedService Interceptor, Default Response's Headers Interceptor, Browser Padding Interceptor Support, Android Interceptor Support, Heartbeat InterceptorSupport, SSE Interceptor Support, JSONP Interceptor Support, Atmosphere JavaScript Protocol, org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor, Browser disconnection detection] mapped to AtmosphereHandler org.atmosphere.config.managed.ManagedAtmosphereHandler
12:03:17,295 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) Browser 0162412d-5015-4b1d-b458-16cf37d4a371 connected to room null.
12:03:26,228 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) user_A just send hey to room null
12:03:38,773 WARN  [org.atmosphere.cpr.AsynchronousProcessor] (http-/0.0.0.0:8080-1) Websocket protocol not supported
12:03:38,807 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-1) Browser 15763962-3c07-4661-98e9-8483a9a51eaa connected to room null.
12:03:38,809 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-4)  just send  to room null
12:03:38,809 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-3)  just send  to room null
12:03:47,163 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) user_B just send hey to room null
12:04:03,194 WARN  [org.atmosphere.cpr.AsynchronousProcessor] (http-/0.0.0.0:8080-1) Websocket protocol not supported
12:04:03,216 INFO  [org.atmosphere.interceptor.HeartbeatInterceptor] (http-/0.0.0.0:8080-1) HeartbeatInterceptor configured with padding value 'X', client frequency 60 seconds and server frequency 0 seconds
12:04:03,217 INFO  [org.atmosphere.cpr.AtmosphereFramework] (http-/0.0.0.0:8080-1) Installed AtmosphereInterceptor [CORS Interceptor Support,  Track Message Size Interceptor using |, UUID Tracking Interceptor, org.atmosphere.interceptor.IdleResourceInterceptor, Atmosphere LifeCycle, @ManagedService Interceptor, Default Response's Headers Interceptor, Browser Padding Interceptor Support, Android Interceptor Support, Heartbeat InterceptorSupport, SSE Interceptor Support, JSONP Interceptor Support, Atmosphere JavaScript Protocol, org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor, Browser disconnection detection] mapped to AtmosphereHandler org.atmosphere.config.managed.ManagedAtmosphereHandler
12:04:03,240 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-1) Browser 97fc9992-b716-49d6-bd63-d012013ab8d8 connected to room null.
12:04:03,244 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-11)  just send  to room null
12:04:03,244 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-10)  just send  to room null
12:04:08,531 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) user_C just send hey to room null
12:04:12,394 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) user_B just send test to room null
12:04:20,694 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-16) user_A just send  sent a message to all chatroom: C to A to room null
12:04:20,695 INFO  [org.atmosphere.samples.chat.ChatRoom] (Atmosphere-Shared-17) user_A just send  sent a message to all chatroom: C to A to room null
12:06:10,375 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) Browser 97fc9992-b716-49d6-bd63-d012013ab8d8 closed the connection from null
12:06:46,527 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-4) Browser 15763962-3c07-4661-98e9-8483a9a51eaa closed the connection from null
12:07:11,706 INFO  [org.atmosphere.samples.chat.ChatRoom] (http-/0.0.0.0:8080-5) Browser 0162412d-5015-4b1d-b458-16cf37d4a371 closed the connection from null
```

I thought that private messaging could be done between any rooms, that's why I send a message from C to A. But even if it don't makes any sense, the room variable is `null`.

**Comment by jfarcand** [comment]
@fanste Thanks
