### ISSUE TITLE
Duplicate resource Could be caused by a dead connection not detected by your server. Replacing the old one with the fresh one

### ISSUE THREAD

**Issue by omidp** [Atmosphere/atmosphere#2102]
I'm using Jboss eap 6.4 with APR and atmosphere 2.4.0 websocket protocol.
after 2 or 3 pushes from javascript I get this exception 

```
JBWEB000238: Exception sending request destroyed lifecycle event to listener instance of class com.sun.faces.config.ConfigureListener: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922) [rt.jar:1.7.0_67]
    at java.util.HashMap$KeyIterator.next(HashMap.java:956) [rt.jar:1.7.0_67]
    at org.apache.catalina.util.Enumerator.<init>(Enumerator.java:101) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.util.Enumerator.<init>(Enumerator.java:67) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.connector.Request.getAttributeNames(Request.java:1189) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.connector.RequestFacade.getAttributeNames(RequestFacade.java:279) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at com.sun.faces.application.WebappLifecycleListener.requestDestroyed(Unknown Source) [jsf-impl-1.2.15.b01-redhat-12.jar:1.2.15.b01-redhat-12]
    at com.sun.faces.config.ConfigureListener.requestDestroyed(Unknown Source) [jsf-impl-1.2.15.b01-redhat-12.jar:1.2.15.b01-redhat-12]
    at org.apache.catalina.core.StandardHostValve.event(StandardHostValve.java:297) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.valves.ValveBase.event(ValveBase.java:185) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.event(StandardEngineValve.java:121) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.event(CoyoteAdapter.java:228) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.coyote.http11.Http11AprProcessor.event(Http11AprProcessor.java:762) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.event(Http11AprProtocol.java:565) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2076) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_67]

11:04:56,841 WARN  [org.atmosphere.cpr.DefaultBroadcaster] (http-localhost/127.0.0.1:8443-4) Duplicate resource Could be caused by a dead connection not detected by your server. Replacing the old one with the fresh one
```

Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent).

is this related to jboss eap or atmosphere ?

**Comment by gnbabu16** [comment]
I am also getting the same error. Could you please suggest me which atmosphere version will suit for
Glassfish 4.0+, Jdk 1.8. I have Filter which triggers on every request.

**Comment by omidp** [comment]
I got this error because I didn't wait for websocket to connect and also I didn't install APR correctly.
I haven't test it on Glassfish but I guess atmosphere 2.4.0 is enough to have fully functional websocket.
