### ISSUE TITLE
Avoid throwing JSR356 exception in modules/cpr unit tests

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere#2106]
Because of the way JSR356 detection and its initialization runs, some unit tests the following exception during the unit tests.

10:03:00.846 ERROR [main] o.a.c.DefaultAsyncSupportResolver [DefaultAsyncSupportResolver.java:238] Real error: Unable to configure jsr356 at that stage. ServerContainer is null
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:51) ~[classes/:na]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_66]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_66]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:232) [classes/:na]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:303) [classes/:na]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:289) [classes/:na]
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2081) [classes/:na]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914) [classes/:na]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:825) [classes/:na]

**Comment by elakito** [comment]
I used the option added with #2104 .
If some adjustment is required there, this patch also needs to be adjusted.
