### ISSUE TITLE
Atmosphere 2.2.3 & Websphere 8 Issue

### ISSUE THREAD

**Issue by javaarch4u** [Atmosphere/atmosphere#2107]
Hi,

Following exception is thrown on the server side when trying to push data from a browser, has anyone seen this behavior?
```java
[12/9/15 12:13:36:032 CST] 00000019 SystemOut     O [2015-12-09 12:13:36 ERROR AsynchronousProcessor:] - Interceptor Atmosphere LifeCycle crashed. Processing will continue with other interceptor.

java.lang.NullPointerException

        at com.ibm.ws.webcontainer.srt.SRTServletRequest.getSession(SRTServletRequest.java:2107) ~[com.ibm.ws.webcontainer.jar:?]

        at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:238) ~[javax.j2ee.servlet.jar:?]

        at org.apache.shiro.web.servlet.ShiroHttpServletRequest.getSession(ShiroHttpServletRequest.java:141) ~[shiro-web-1.1.0.jar:?]

        at org.atmosphere.cpr.AtmosphereRequest.getSession(AtmosphereRequest.java:784) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.SessionTimeoutSupport.restoreTimeout(SessionTimeoutSupport.java:69) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:765) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AtmosphereResourceImpl.dirtyClose(AtmosphereResourceImpl.java:856) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.DefaultBroadcaster.addAtmosphereResource(DefaultBroadcaster.java:1353) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:400) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor.postInspect(AtmosphereResourceLifecycleInterceptor.java:145) ~[atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AsynchronousProcessor.postInterceptors(AsynchronousProcessor.java:336) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:202) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2069) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:211) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:197) [atmosphere-runtime-2.2.3.jar:2.2.3]

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:575) [javax.j2ee.servlet.jar:?]

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668) [javax.j2ee.servlet.jar:?]

        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1188) [com.ibm.ws.webcontainer.jar:?]

        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:763) [com.ibm.ws.webcontainer.jar:?]

        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:454) [com.ibm.ws.webcontainer.jar:?]

        at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178) [com.ibm.ws.webcontainer.jar:?]

        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:125) [com.ibm.ws.webcontainer.jar:?]

        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:92) [com.ibm.ws.webcontainer.jar:?]

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.1.0.jar:?]

       at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:359) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:275) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.1.0.jar:1.1.0]

        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.1.0.jar:1.1.0]

        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:344) [shiro-core-1.1.0.jar:1.1.0]

        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:272) [shiro-web-1.1.0.jar:?]

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81) [shiro-web-1.1.0.jar:?]

        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:192) [com.ibm.ws.webcontainer.jar:?]

        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:89) [com.ibm.ws.webcontainer.jar:?]
```
On the client side, following error is seen

"No suspended connection available. Make sure atmosphere.sunscribe has been called and request.onOpen invoked before invoking this method" the method is atmosphere.AtmosphereRequest.push

**Comment by elakito** [comment]
Isn't the NPE coming from com.ibm.ws.webcontainer.srt.SRTServletRequest.getSession(SRTServletRequest.java:2107)? It looks like this is not an atmosphere issue.
http://www-01.ibm.com/support/docview.wss?uid=swg1PM61525
