### ISSUE TITLE
 Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport

### ISSUE THREAD

**Issue by ingwarsw** [Atmosphere/atmosphere#2111]
Glassfish 4.1 (Payara 4.1.1)
Atmosphere 2.4.1 (2.4.0 too, works ok with 2.3.6)
RichFaces 4.5.12

Od deploying application:
<pre>
(org.atmosphere.cpr.AtmosphereFramework:1762): Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol

(org.atmosphere.container.JSR356AsyncSupport:68): JSR 356 Mapping path /__richfaces_push

(org.atmosphere.cpr.DefaultAsyncSupportResolver:237): Failed to create AsyncSupport class: class 
org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException

(org.atmosphere.cpr.DefaultAsyncSupportResolver:241): Real error: Not in 'deploy' scope.

java.lang.IllegalStateException: Not in 'deploy' scope.
        at org.glassfish.tyrus.server.TyrusServerContainer.addEndpoint(TyrusServerContainer.java:195)
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:74)
        at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:234)
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:306)
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:292)
        at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2080)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
        at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:75)
        at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:84)
        at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:80)
        at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:75)
        at org.richfaces.webapp.PushServlet.init(PushServlet.java:67)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1583)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1382)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5732)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5977)
.....
</pre>

And then on browser

<pre>
WebSocket connection to 'ws://host:8080/root/__richfaces_push?__richfacesPushAsync=1&pushSessionId=26ca805b-d82a-438a-b3e1-716262d9b791&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.13-jquery&X-Atmosphere-Transport=websocket&X-atmo-protocol=true' failed: Error during WebSocket handshake: Unexpected response code: 501
jquery-atmosphere.js.xhtml:3158 Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent).
jquery-atmosphere.js.xhtml:3158 Websocket closed, wasClean: false
jquery-atmosphere.js.xhtml:3158 Websocket failed. Downgrading to Comet and resending
</pre>

**Comment by elakito** [comment]
@ingwarsw 
i don't know what exactly the issue is but it could be related to the way how atmosphere and jsr356 are setup for 2.4.x. In the current snapshot 2.4.2-SNAPSHOT, there is an option to go back to the 2.3.x behavior (see #2104). There is a new init parameter "org.atmosphere.suppressDetectingJSR356" that can be set to true to suppress this 2.4.x's jsr356 detection behavior.

@jfarcand 
we should release 2.4.2 before the holidays start. how do you think?

**Comment by elakito** [comment]
2.4.2 is out.
you can set parameter "org.atmosphere.websocket.suppressJSR356" to true to solve this issue.

**Comment by davidandradeb** [comment]
I worked with:
PAYARA 5.181
> <servlet>
>         <servlet-name>Push Servlet</servlet-name>
>         <servlet-class>org.primefaces.push.PushServlet</servlet-class>
>         
>         <init-param>
>             <param-name>org.atmosphere.cpr.asyncSupport</param-name>
>             <param-value>org.atmosphere.container.GlassFishServ30WebSocketSupport</param-value>
>         </init-param>
>         <init-param>
>             <param-name>org.atmosphere.websocket.suppressJSR356</param-name>
>             <param-value>true</param-value>
>         </init-param>
>         
>         <async-supported>true</async-supported>
>     </servlet>
>     <servlet-mapping>
>         <servlet-name>Push Servlet</servlet-name>
>         <url-pattern>/primepush/*</url-pattern>
>     </servlet-mapping>
