### ISSUE TITLE
AtmosphereFramework failing to initialize on jetty server startup

### ISSUE THREAD

**Issue by timols** [Atmosphere/atmosphere#2126]
We're running Atmosphere with Guice and Jersey in a Dropwizard application and are seeing issues on startup related to the ScheduledThreadPoolExecutor. Specifically we're using the following versions:

```
        <atmosphere.guice.version>2.3.1</atmosphere.guice.version>
        <atmosphere.jersey.version>2.3.4</atmosphere.jersey.version>
```

On startup, the application fails with the following stacktrace:

```
2016-02-05T06:39:20,229+11:00 [] [] [] [] [main] ERROR o.a.c.AtmosphereFramework - Failed to initialize Atmosphere Framework
javax.servlet.ServletException: org.atmosphere.cpr.BroadcasterFactory$BroadcasterCreationException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2fc2b252 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@cc3abaa[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 1]
	at org.atmosphere.cpr.AtmosphereFramework.loadConfiguration(AtmosphereFramework.java:1561) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:906) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:835) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:74) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:83) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:79) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:74) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:540) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:349) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:812) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:732) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [app.jar:1.0.2-SNAPSHOT]
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:89) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:131) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:233) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.Server.start(Server.java:342) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.server.Server.doStart(Server.java:290) [app.jar:1.0.2-SNAPSHOT]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [app.jar:1.0.2-SNAPSHOT]
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [app.jar:1.0.2-SNAPSHOT]
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [app.jar:1.0.2-SNAPSHOT]
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [app.jar:1.0.2-SNAPSHOT]
	at io.dropwizard.cli.Cli.run(Cli.java:70) [app.jar:1.0.2-SNAPSHOT]
	at io.dropwizard.Application.run(Application.java:72) [app.jar:1.0.2-SNAPSHOT]
	at com.app.http.service.ApiService.main(ApiService.java:67) [app.jar:1.0.2-SNAPSHOT]
Caused by: org.atmosphere.cpr.BroadcasterFactory$BroadcasterCreationException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2fc2b252 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@cc3abaa[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 1]
	at org.atmosphere.cpr.DefaultBroadcasterFactory.createBroadcaster(DefaultBroadcasterFactory.java:163) ~[app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.DefaultBroadcasterFactory.lookup(DefaultBroadcasterFactory.java:224) ~[app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.DefaultBroadcasterFactory.get(DefaultBroadcasterFactory.java:136) ~[app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereFramework.detectSupportedFramework(AtmosphereFramework.java:1631) [app.jar:1.0.2-SNAPSHOT]
	at org.atmosphere.cpr.AtmosphereFramework.loadConfiguration(AtmosphereFramework.java:1555) [app.jar:1.0.2-SNAPSHOT]
	... 43 common frames omitted
```

This issue appears to be intermittent and we're still trying to track down the cause. It appears that there is a task that is scheduled on startup that is perhaps running into a timing problem, based on the stacktrace?

I'll provide more information as needed, but any direction is very welcome!

**Comment by elakito** [comment]
@timols based on the error message i think the executorpool was being shutdown when the new job was submitted. i don't know why and when this happened.

**Comment by jfarcand** [comment]
@timols Closing as user error, please re-open with a test case available on Github if possible.
