### ISSUE TITLE
SessionSupport.sessionDestroyed tries to create new session and fails when response comitted

### ISSUE THREAD

**Issue by mikecollard** [Atmosphere/atmosphere#2137]
```
@Override
    public void sessionDestroyed(HttpSessionEvent se) {
        logger.trace("Session destroyed");
        try {
            HttpSession s = se.getSession();
            if (BroadcasterFactory.getDefault() != null) {
                for (Broadcaster b : BroadcasterFactory.getDefault().lookupAll()) {
                    for (AtmosphereResource r : b.getAtmosphereResources()) {
                        if (r.session() != null && r.session().getId().equals(s.getId())) {
                            AtmosphereResourceImpl.class.cast(r).session(null);
                        }
                    }
                } 
            }
        } catch (Throwable t) {
            logger.warn("", t);
        }
    }
```

Seems this should be using r.session(false) instead of just r.session()
r.session() never returns null 
and if the response has been committed already it blows up with following stack (tomcat)

```
 java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2924) ~[catalina.jar:7.0.53]
	at org.apache.catalina.connector.Request.getSession(Request.java:2300) ~[catalina.jar:7.0.53]
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897) ~[catalina.jar:7.0.53]
	at org.atmosphere.cpr.AtmosphereRequest.getSession(AtmosphereRequest.java:794) ~[atmosphere-runtime-2.2.9.jar:2.2.9]
	at org.atmosphere.cpr.AtmosphereResourceImpl.session(AtmosphereResourceImpl.java:849) ~[atmosphere-runtime-2.2.9.jar:2.2.9]
	at org.atmosphere.cpr.AtmosphereResourceImpl.session(AtmosphereResourceImpl.java:890) ~[atmosphere-runtime-2.2.9.jar:2.2.9]
	at org.atmosphere.cpr.SessionSupport.sessionDestroyed(SessionSupport.java:49) ~[atmosphere-runtime-2.2.9.jar:2.2.9]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:806) [catalina.jar:7.0.53]
	at org.apache.catalina.ha.session.DeltaSession.expire(DeltaSession.java:478) [catalina-ha.jar:7.0.53]
	at org.apache.catalina.ha.session.DeltaSession.expire(DeltaSession.java:442) [catalina-ha.jar:7.0.53]
	at org.apache.catalina.ha.session.DeltaSession.isValid(DeltaSession.java:405) [catalina-ha.jar:7.0.53]
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:532) [catalina.jar:7.0.53]
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:517) [catalina.jar:7.0.53]
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1352) [catalina.jar:7.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530) [catalina.jar:7.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540) [catalina.jar:7.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540) [catalina.jar:7.0.53]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519) [catalina.jar:7.0.53]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by elakito** [comment]
@mikecollard i think you are right. Could you send a PR? thanks.
