### ISSUE TITLE
ReflectorServletProcessor#getServlet() is expected to be non-null

### ISSUE THREAD

**Issue by martin-g** [Atmosphere/atmosphere#2142]
While testing the fix for #2140 I bumped on:
```
WARN  - Universe                   - More than one Universe configured. Universe class will gives wrong object reference org.atmosphere.cpr.DefaultBroadcasterFactory@3623da02
WARN  - Universe                   - More than one Universe configured. Universe class will gives wrong object reference org.atmosphere.cpr.DefaultAtmosphereResourceFactory@331afbc1
WARN  - Universe                   - More than one Universe configured. Universe class will gives wrong object reference org.atmosphere.cpr.AtmosphereFramework@7db92c05
ERROR - Utils                      - 
java.lang.NullPointerException
	at org.atmosphere.util.Utils.requestScopedInjection(Utils.java:305)
	at org.atmosphere.cpr.AtmosphereFramework$AtmosphereHandlerWrapper$1.started(AtmosphereFramework.java:324)
	at org.atmosphere.cpr.AtmosphereConfig.initComplete(AtmosphereConfig.java:225)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:958)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:75)
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:84)
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:80)
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:75)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4882)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5169)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1585)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:463)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:413)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1471)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1312)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1404)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:832)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$81(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The line is:
```java
return ((InjectableObjectFactory)InjectableObjectFactory.class.cast(config.framework().objectFactory())).needRequestScoped(injectWith(h).getClass());
```
Not very easy to guess what is `null` here.

Fired the debugger and it is the result of `org.atmosphere.util.Utils#injectWith(org.atmosphere.cpr.AtmosphereHandler)` where it uses `((ReflectorServletProcessor)ReflectorServletProcessor.class.cast(h)).getServlet()` which as we know from #2140 is `null` in my case.

**Comment by elakito** [comment]
other than this, is it now working?
if so, we can add an NPE guard here to avoid logging this error.
thanks.

**Comment by martin-g** [comment]
Now it fails with:
```
org.apache.wicket.WicketRuntimeException: The Atmosphere BroadcasterFactory has no Broadcasters, something is wrong with your Atmosphere configuration.
	at org.apache.wicket.atmosphere.EventBus.lookupDefaultBroadcaster(EventBus.java:179)
	at org.apache.wicket.atmosphere.EventBus.getBroadcaster(EventBus.java:242)
	at org.apache.wicket.atmosphere.EventBus.post(EventBus.java:440)
	at org.apache.wicket.examples.atmosphere.AtmosphereApplication$1.run(AtmosphereApplication.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

but this is a problem in Wicket.
Until Atmosphere 2.x we were using ` BroadcasterFactory.getDefault()` but this has been deprecated and removed. Now I have to debug what is wrong with the new code.
```java
BroadcasterFactory factory = framework.getBroadcasterFactory();
		Collection<Broadcaster> allBroadcasters = factory.lookupAll();
		if (allBroadcasters.isEmpty())
		{
			throw new WicketRuntimeException(
					"The Atmosphere BroadcasterFactory has no Broadcasters, "
							+ "something is wrong with your Atmosphere configuration.");
		}
		return allBroadcasters.iterator().next();
```
It must be a configuration issue.

**Comment by elakito** [comment]
now, this case is gracefully handled and not exception is dumped.

**Comment by martin-g** [comment]
Thanks!
I'll test it soon!
