### ISSUE TITLE
HeartbeatInterceptor should not schedule a task if request fails

### ISSUE THREAD

**Issue by orange-buffalo** [Atmosphere/atmosphere#2143]
Assume `HeartbeatInterceptor` is enabled with default configuration and the first request fails:
```
(http-/127.0.0.1:8180-3) JBWEB000236: Servlet.service() for servlet Push Servlet threw exception: java.lang.IllegalStateException: JBWEB000048: The servlet or filters that are being used by this request do not support async operation
	at org.apache.catalina.connector.Request.startAsync(Request.java:3205) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:936) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:450) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.atmosphere.cpr.AtmosphereRequestImpl.startAsync(AtmosphereRequestImpl.java:615) [atmosphere-runtime-native-2.4.0.jar:2.4.0]
	at org.atmosphere.container.Servlet30CometSupport.suspend(Servlet30CometSupport.java:95) [atmosphere-runtime-native-2.4.0.jar:2.4.0]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:70) [atmosphere-runtime-native-2.4.0.jar:2.4.0]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2281) [atmosphere-runtime-native-2.4.0.jar:2.4.0]
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:199) [atmosphere-runtime-native-2.4.0.jar:2.4.0]
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:185) [atmosphere-runtime-native-2.4.0.jar:2.4.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.jar:1.0.2.Final-redhat-2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.deltaspike.servlet.impl.produce.RequestResponseHolderFilter.doFilter(RequestResponseHolderFilter.java:63) [deltaspike-servlet-module-impl-1.5.2.jar:1.5.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
``` 
Although request fails and connection is not properly established, `HeartbeatInterceptor` still schedules the heartbeat task and writes into `AtmosphereResponse` after `interval`. 
This causes interesting side-effects on JBoss server, namely that some other http response (of request executed after `interval`), even if it is not Atmosphere-related, receives the heartbeat message content `data:1|X` (JBoss uses a pool of `HttpResponse`).

The expected behavior is that there is no scheduled task of `HeartbeatInterceptor` in case of request failure.  

Environment: JBoss EAP 6.4, Atmosphere 2.4.0 (coming with Primefaces 5.3).

**Comment by dmaidaniuk** [comment]
This bug is really major. We also have same problem with JBoss EAP 6.4 and PrimeFaces 5.3 shipped with Atmosphere 2.4.0.

**Comment by jfarcand** [comment]
Fix the exception at first place, e.g the exception `The servlet or filters that are being used by this request do not support async operation` is *NOT* from Atmosphere (Google it for explanation) but from a misconfigured application. This is not a bug in Atmosphere.

**Comment by dmaidaniuk** [comment]
Well, issue isn't about where exception happens but about Atmosphere heartbeat task for failed request. And this is a bug in framework.

**Comment by orange-buffalo** [comment]
Agree with @dmaidaniuk . Error handling is an integral part of any code. `HeartbeatInterceptor` does not handle errors correctly, which causes unexpected behavior and `magic` bugs after that. We spent a day to find out the cause of issue with heart-beat data in random responses from server.

**Comment by jfarcand** [comment]
Contribution welcomed...I still fail why Atmosphere should fix bugs that occurs outside of its scope. But I'm open to a pull request :-)
