### ISSUE TITLE
DeploymentException (WELD-001408) with injected BroadcasterFactory

### ISSUE THREAD

**Issue by Basti237** [Atmosphere/atmosphere#2167]
I'm using atmosphere-runtime 2.4.4 with atmosphere-cdi 2.4.2 on JBoss EAP 6.4.7. Atmosphere is used in an ear-file with the following structure:
- ear-file
  - war-file
    - WEB-INF
      - lib
        - atmosphere-runtime-2.4.4.jar
        - atmosphere-cdi-2.4.2.jar
      - classes
        - _package-path_
          - TestDataBroadcaster.class
      - beans.xml

The problem is that if I try to inject the BroadcasterFactory, like described [here](https://github.com/Atmosphere/atmosphere/wiki/Getting-BroadcasterFactory-and-AtmosphereResourceFactory-with-2.2-and-newer) & [also here](https://github.com/Atmosphere/atmosphere/wiki/Injecting-Atmosphere-components-and-factories-using-the-javax.inject.Inject), in the TestDataBraodcaster class I'm getting the following exception while starting the JBoss-server.

```
2016.06.01 08:00:48,121 ERROR [org.jboss.msc.service.fail] (user=, pid=, institution=, rolle=, MSC service thread 1-15) MSC000001: Failed to start service jboss.deployment.unit."mywar.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."mywar.war".WeldStartService: Failed to start service
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1936) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [BroadcasterFactory] with qualifiers [@Default] at injection point [[field] @Inject private default.TestAdapter.broadcasterFactory]
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:315)
    at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
    at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:147)
    at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
    at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
    at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
    at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
    at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:65)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
    ... 3 more
```

Furthermore it's not possible to inject the Broadcaster with inject and `@Named` annotation.

I've also tried to use a ManagedService (with `@ManagedService`) together with an `@ApplicationScoped` TestAdapter. The injection of the TestAdapter is only successful if I also implement the class TestAdapterInjectalbe and add the configuration file _'/META-INF/services/org.atmosphere.inject.Injectable'_. But if I try to inject
the BroadcasterFactory in TestAdapter I get the DeploymentException "WELD-001408 Unsatisfied dependencies".

**Code-snippet:**

``` java
@ManagedService(path = "/myservice")
public class MyTestService {
    @Inject
    private TestAdapter adapter;
}

public class TestAdapterInjectalbe implements Injectable<TestAdapter> {
   ...
}

@ApplicationScoped
public class TestAdapter {
    @Inject
    private BroadcasterFactory broadcasterFactory;
}
```

**Comment by mkefd** [comment]
Same for me. It seems that with atmosphere-cdi included annotations processed by atmosphere like `Inject  `or `PathParam` stop working. Removing the atmosphere-cdi makes them work again!

@jfarcand could you please clarify this?

atmosphere-runtime 2.4.7
atmosphere-cdi 2.4.3
glassfish 4.1, wildfly 10.2

**Comment by Igogrek** [comment]
Having the exact same issue. 
With atmosphere-cdi all of the `Inject` usages are broken.
Config which is passed to AtmosphereProducers class configure method isn't null, yet when getBroadcasterFactory() (for example) is called it is null, so it causes NPE

**Comment by jfarcand** [comment]
@Igogrek @mkefd  Unfortunately I don't have any cycle to look at this issue...pull request welcomed!

**Comment by ak80** [comment]
Any news on this? Is there a workaround? Without atmosphere-cdi it doesnt work at all for me. I tried to get the Atmosphere Framework as described in https://github.com/Atmosphere/atmosphere/wiki/Getting-BroadcasterFactory-and-AtmosphereResourceFactory-with-2.2-and-newer but that seems broken too.
