### ISSUE TITLE
NullPointerException on Atmosphere init

### ISSUE THREAD

**Issue by neopsis** [Atmosphere/atmosphere#2170]
Atmosphere 2.2.7 ( but still there in the latest release ):

```
Caused by: java.lang.NullPointerException
 at org.atmosphere.cpr.AtmosphereFramework.configureAnnotationPackages(AtmosphereFramework.java:1001)
 at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:865)
```
Code at line 1001:
`annotationPackages.add(Processor.class.getPackage().getName());`

From class.getPackage() documentation:

> Returns:the package of the class, or null if no package information is available from the archive or codebase

The code should not crash if getPackage() returns null.

**Comment by jfarcand** [comment]
Well I won't fix that as coding without package it's not really an option, event ifs allowed.
