### ISSUE TITLE
When I left the page is always throw NullPointerException

### ISSUE THREAD

**Issue by ansjsun** [Atmosphere/atmosphere#2178]
i used it in jetty9 !

version is 'org.atmosphere:atmosphere-runtime:2.4.4'

when i left the page , 

it throw 

```
java.lang.NullPointerException
    at org.atmosphere.util.Utils.injectWith(Utils.java:250)
    at org.atmosphere.util.Utils.inject(Utils.java:233)
    at org.atmosphere.cpr.AsynchronousProcessor.invokeAtmosphereHandler(AsynchronousProcessor.java:539)
    at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:486)
    at org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:77)
    at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:340)
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:201)
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115)
    at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:68)
    at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:170)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2287)
    at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:191)
    at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:177)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
    at org.nutz.mvc.NutFilter.nextChain(NutFilter.java:224)
```

i find log it is AsynchronousProcessor in line 486

```
                invokeAtmosphereHandler(impl);
            } catch (Throwable ex) {
                // Something wrong happened, ignore the exception
                logger.error("Failed to cancel resource: {}", impl.uuid(), ex);
            } finally {
```

it allways write exception in my log , can i not log it only err , with out print exception

**Comment by saikiran939** [comment]
My two cents - in our implementations we have faced such occurrences of exceptions getting spewed to log files, we had to change the logging level in the code to 'trace'
