### ISSUE TITLE
NPE: Interceptor Atmosphere LifeCycle crashed. Processing will continue with other interceptor.

### ISSUE THREAD

**Issue by abannany** [Atmosphere/atmosphere#2188]
An error is thrown after an browser a refresh (clicking on F5 or Cntr-F5). After that an browser client reconnect.

This error is thrown on an WAS 8.5.5.8.

Stacktrace:
java.lang.NullPointerException: null
at com.ibm.ws.webcontainer.srt.SRTServletRequest$SRTServletRequestHelper.access$200(SRTServletRequest.java:3211)
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.removeAttribute(SRTServletRequest.java:829)
	at org.atmosphere.cpr.AtmosphereRequestImpl.removeAttribute(AtmosphereRequestImpl.java:659)
	at org.atmosphere.container.Servlet30CometSupport.endAsyncContext(Servlet30CometSupport.java:136)
	at org.atmosphere.container.Servlet30CometSupport.complete(Servlet30CometSupport.java:119)
	at org.atmosphere.container.Servlet30CometSupport.complete(Servlet30CometSupport.java:46)
	at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:806)
	at org.atmosphere.cpr.AtmosphereResourceImpl.dirtyClose(AtmosphereResourceImpl.java:910)
	at org.atmosphere.cpr.DefaultBroadcaster.addAtmosphereResource(DefaultBroadcaster.java:1370)
	at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:401)
	at org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor.postInspect(AtmosphereResourceLifecycleInterceptor.java:145)
	at org.atmosphere.cpr.AsynchronousProcessor.postInterceptors(AsynchronousProcessor.java:374)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:230)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:68)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2287)
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:191)
	at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:177)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)

**Comment by SreecharanChallagundla** [comment]
Hello Abannany,

Didn't you any solution to this problem...

Thanks
