### ISSUE TITLE
ClassCastException in AsynchronousProcessor

### ISSUE THREAD

**Issue by pohualin** [Atmosphere/atmosphere#2204]
Hi Atmosphere folks,

We are facing an issue using Atmosphere runtime 2.4.5 with Websphere 8.5. Below is the exception we captured on our server log. Could you please kindly let us know if there is something wrong with our code?
```java
2016-08-16 16:21:15 [WebContainer : 2] ERROR UUID= org.atmosphere.cpr.AsynchronousProcessor - (AsynchronousProcessor.java:376) - Interceptor Atmospher
e LifeCycle crashed. Processing will continue with other interceptor.
java.lang.ClassCastException: java.lang.String incompatible with org.atmosphere.cpr.AtmosphereResource
        at org.atmosphere.cpr.AtmosphereRequestImpl.resource(AtmosphereRequestImpl.java:833)
        at org.atmosphere.cpr.AtmosphereRequestImpl.getSession(AtmosphereRequestImpl.java:663)
        at org.atmosphere.cpr.SessionTimeoutSupport.restoreTimeout(SessionTimeoutSupport.java:69)
        at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:817)
        at org.atmosphere.cpr.AtmosphereResourceImpl.dirtyClose(AtmosphereResourceImpl.java:910)
        at org.atmosphere.cpr.DefaultBroadcaster.addAtmosphereResource(DefaultBroadcaster.java:1370)
        at org.atmosphere.plugin.hazelcast.HazelcastBroadcaster.addAtmosphereResource(HazelcastBroadcaster.java:94)
        at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:401)
        at org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor.postInspect(AtmosphereResourceLifecycleInterceptor.java:145)
        at org.atmosphere.cpr.AsynchronousProcessor.postInterceptors(AsynchronousProcessor.java:374)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:230)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115)
        at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:68)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2287)
        at org.atmosphere.spring.bean.AtmosphereSpringServlet.doPost(AtmosphereSpringServlet.java:75)
        at org.atmosphere.spring.bean.AtmosphereSpringServlet.doGet(AtmosphereSpringServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1232)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:781)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:480)
        at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:79)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:940)
        at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
        at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
        at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
        at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
        at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
        at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
        at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
        at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
        at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
        at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
        at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
        at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1881)
```

**Comment by elakito** [comment]
@pohualin if what you are saying is correct (you say you are using atmosphere-2.4.5), it looks like there is some inconsistency in your system. In atmoshere-2.4.5, AtmosphereRequestImpl.java:833 doesn't point to the resource method.

**Comment by pohualin** [comment]
@elakito You're right. I double check our application and the atmosphere version is 2.4.3. Sorry for the confusion.

**Comment by elakito** [comment]
@pohualin Ok. The exception matches the 2.4.3 code. But I don't know who is putting a string as the atmosphere resource object in the attributes map (stored with key org.atmosphere.cpr.AtmosphereResource).
