### ISSUE TITLE
Jboss EAP 6.4 - JSR356AsyncSupport error: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null.

### ISSUE THREAD

**Issue by Quentame** [Atmosphere/atmosphere#2213]
Hello !

@stour and I are working on implementing **Atmosphere on JBoss EAP 6.4.5**.

On our **JEE 6** application, we are using **PrimeFaces 5.2.13** which has simplified implementations of Atmosphere.
**JDK 1.7**
**JVM 1.8**

I implemented Atmosphere 2.3.8 and I saw on my console:
```
WebSocket connection to 'wss://localhost:8443/framework-ui-jsf2-showcase/primepush/tod…ransport=websocket&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true' failed: Error during WebSocket handshake: Unexpected response code: 501
Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent).
Websocket closed, wasClean: false
Websocket failed. Downgrading to Comet and resending
```

So the server "push" works but **it is always using Long Polling instead of WebSocket** (tested on Chrome 53 and Firefox 50).

On the server log, I'v got the famous error "org.atmosphere.container.JSR356AsyncSupport, error: java.lang.IllegalStateException: **Unable to configure jsr356 at that stage. ServerContainer is null**":
With **Atmosphere 2.3.8** (native or not)
```java
14:36:27,333 INFO  [org.atmosphere.cpr.AtmosphereFramework] (ServerService Thread Pool -- 60) Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
14:36:27,348 ERROR [org.atmosphere.cpr.DefaultAsyncSupportResolver] (ServerService Thread Pool -- 60) Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
14:36:27,348 ERROR [org.atmosphere.cpr.DefaultAsyncSupportResolver] (ServerService Thread Pool -- 60) Real error: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
14:36:27,348 ERROR [org.atmosphere.cpr.DefaultAsyncSupportResolver] (ServerService Thread Pool -- 60) Switching to BlockingIO
14:36:27,348 INFO  [org.atmosphere.cpr.AtmosphereFramework] (ServerService Thread Pool -- 60) Installing Default AtmosphereInterceptors

```

With **Atmosphere 2.4.6** (native or not)
```java
15:40:39,255 INFO  [org.atmosphere.cpr.AtmosphereFramework] (ServerService Thread Pool -- 54) Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
15:40:39,271 WARN  [org.atmosphere.cpr.DefaultAsyncSupportResolver] (ServerService Thread Pool -- 54) Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
15:40:39,271 ERROR [org.atmosphere.cpr.DefaultAsyncSupportResolver] (ServerService Thread Pool -- 54) Real error: Unable to configure jsr356 at that stage. ServerContainer is null: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:51) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [rt.jar:1.8.0_40]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:234) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:306) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:292) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2082) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.primefaces.push.PushServlet.configureFramework(PushServlet.java:84) [primefaces-5.2.13.jar:5.2.13]
	at org.primefaces.push.PushServlet.configureFramework(PushServlet.java:36) [primefaces-5.2.13.jar:5.2.13]
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:84) [atmosphere-runtime-native-2.4.6.jar:2.4.6]
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1206) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1112) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:3593) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3802) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:163) [jboss-as-web-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:61) [jboss-as-web-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:96) [jboss-as-web-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)

15:40:39,287 WARN  [org.atmosphere.cpr.DefaultAsyncSupportResolver] (ServerService Thread Pool -- 54) Found multiple containers, please specify which one to use: org.atmosphere.container.JBossWebCometSupport, org.atmosphere.container.TomcatCometSupport, org.atmosphere.container.NettyCometSupport,  until you do, Atmosphere will use:class org.atmosphere.container.JBossWebCometSupport
15:40:39,287 INFO  [org.atmosphere.cpr.AtmosphereFramework] (ServerService Thread Pool -- 54) Installing Default AtmosphereInterceptors
```

In addition, in 2.4.6 (2.4.x I think) only, there is one more JavaScript error which made the **Long Polling not working** ... so we are using 2.3.8 
Here the JavaScript error:
```
GET https://localhost:8443/framework-ui-jsf2-showcase/primepush/t…ng&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1473947025239 500 (Internal Server Error)
```

So unfortunately I can't use WebSockets !

My actual files:
pom.xml
```xml
<dependency>
    <groupId>org.atmosphere</groupId>
    <artifactId>atmosphere-runtime</artifactId>
    <version>2.3.8</version>
</dependency>
```

standalone.xml (JBoss config)
```xml
<subsystem xmlns="urn:jboss:domain:web:2.2" default-virtual-server="default-host" native="false">
    <connector name="http" protocol="HTTP/1.1" scheme="http" socket-binding="http" redirect-port="8443"/>
    <connector name="https" protocol="HTTP/1.1" scheme="https" socket-binding="https" enable-lookups="false" secure="true">
        <ssl name="ssl" password="corp" certificate-key-file="${jboss.server.config.dir}/store.jks" protocol="TLSv1" verify-client="false"/>
        <!-- <ssl name="ssl" password="corp" certificate-file="${jboss.server.config.dir}/cert.pem" certificate-key-file="${jboss.server.config.dir}/key.pem" protocol="TLSv1" verify-client="false"/> -->
    </connector>
    <virtual-server name="default-host" enable-welcome-root="true">
        <alias name="localhost"/>
    </virtual-server>
</subsystem>
```

jboss-web.xml
```xml
<jboss-web version="7.2"
        xmlns="http://www.jboss.com/xml/ns/javaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.jboss.com/xml/ns/javaee schema/jboss-web_7_2.xsd">
        <enable-websockets>true</enable-websockets>
</jboss-web>
```

To solve those problems, I search on the Wiki and Google, but those links did not solve the problem:
* [Atmosphere Wiki - Installing JBoss WebSocket Support (January 2015)](https://github.com/Atmosphere/atmosphere/wiki/Installing-JBoss-WebSocket-Support)
* [Atmosphere Wiki - Enabling WebSocket Support in JBoss EAP 6.3 and up (February 2015)](https://github.com/Atmosphere/atmosphere/wiki/Enabling-WebSocket-Support-in-JBoss-EAP-6.3-and-up)
* [Atmosphere Wiki - Installing AtmosphereServlet with or without native support (January 2015)](https://github.com/Atmosphere/atmosphere/wiki/Installing-AtmosphereServlet-with-or-without-native-support)
* [RedHat Support - Does JBoss EAP support the use of WebSockets? (April 2016)](https://access.redhat.com/solutions/47442)
* [IT CROWD - Atmosphere configuration with JBoss AS 7.1.1 (November 2013)](http://blog.itcrowd.pl/2013/11/atmosphere-configuration-with-jboss-as.html)
* [Vaadin Support - Configuring push for your environment (June 2013)](https://vaadin.com/wiki?p_p_id=36&p_p_lifecycle=0&p_p_state=pop_up&p_p_mode=view&_36_struts_action=%2Fwiki%2Fview&p_r_p_185834411_nodeName=vaadin.com+wiki&p_r_p_185834411_title=Configuring+push+for+your+environment#section-Configuring+push+for+your+environment-JBoss+EAP+6.4+)

In addition, we saw that JBoss 6.4 natively supports WebSockets:

1. [Download the native components (direct link from RedHat)](https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=36993)
2. Unzip and install those components (only the folder win-x86_64 in \jboss-eap-6.4\modules\system\layers\base\org\jboss\as\web\main\lib\) into $MODULE_PATH$/org/jboss/as/web/main/lib as described [here (RedHat support)](https://access.redhat.com/solutions/222023)
3. [Download the jboss-websocket-hello from GitHub](https://github.com/jboss-developer/jboss-eap-quickstarts/tree/6.4.x/websocket-hello)
4. Launch it and test native WebSocket

Since we had this, we add Atmosphere (tested with 2.3.8 and 2.4.6) and we **obtain the same error**, so the problem is not coming from PrimeFaces.

How can I fix this ? (and **use WebSocket with JBoss 6.4.5**)

**Comment by stour** [comment]
We eventually activated WebSocket support in Atmosphere on JBoss EAP 6.4.5 after following next configuration steps:
1. Install native components provided by JBoss (link in above message).
2. In standalone.xml (or domain.xml) set `native` parameter to true.
3. In your web.xml in the servlet section of your AtmosphereServlet add param to force using `JBossAsyncSupportWithWebSocket`:
```xml
<init-param>
       <param-name>org.atmosphere.cpr.asyncSupport</param-name>
       <param-value>org.atmosphere.container.JBossAsyncSupportWithWebSocket</param-value>
</init-param>
```
4. In your pom.xml:
```xml
<dependency>
    <groupId>org.atmosphere</groupId>
    <artifactId>atmosphere-runtime-native</artifactId>
    <version>2.3.8</version>
</dependency>
<dependency>
    <groupId>org.atmosphere.jboss.as</groupId>
    <artifactId>jboss-as-websockets</artifactId>
    <version>0.5</version>
</dependency>
```

With this configuration Websockets are successfully used for push events. However we are still having issues when using atmosphere 2.4.6. Using atmosphere 2.3.8 works fine. @Quentame can provide more details.

**Comment by saikiran939** [comment]
I see that issue is closed, but EAP JBOSS 6.4 supports WebSockets out of the box.  Can you leverage it ?

**Comment by jfarcand** [comment]
@saikiran939 Pull request welcomed :-)

**Comment by saikiran939** [comment]
If you want to use JSR356 websocket implementation, use below configurations:

1. put <enable-websockets>true</enable-websockets> just before </jboss-web> in your jboss-web.xml file
2. change connector configuration in standalone-full.xml to NIO connector protocol as:

Change:
<connector name="http" protocol="HTTP/1.1" scheme="http" socket-binding="http"/>  to
<connector name="http" protocol="org.apache.coyote.http11.Http11NioProtocol" scheme="http" socket-binding="http"/>


This configuration works for JBOSS EAP 6.3.0 too.
