### ISSUE TITLE
Unable to create org.atmosphere.container.Jetty9AsyncSupportWithWebSocket

### ISSUE THREAD

**Issue by chizar** [Atmosphere/atmosphere#2248]
Please add support of the last jetty 9.3.16.v20170120 version.

Jetty guys have removed constructor
`org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(Lorg/eclipse/jetty/websocket/api/WebSocketPolicy;)` 

so 

`atmosphere-runtime-2.2.9  org/atmosphere/container/Jetty9AsyncSupportWithWebSocket.java:107` 

`webSocketFactory` = new `WebSocketServerFactory(policy)`

crashes with exception:

```javax.servlet.ServletException: java.lang.IllegalArgumentException: Unable to create org.atmosphere.container.Jetty9AsyncSupportWithWebSocket
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:912)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:780)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:220)
	... 34 more
Caused by: java.lang.IllegalArgumentException: Unable to create org.atmosphere.container.Jetty9AsyncSupportWithWebSocket
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:249)
	at org.atmosphere.cpr.AtmosphereFramework.doInitParams(AtmosphereFramework.java:1331)
	at org.atmosphere.cpr.AtmosphereFramework.doInitParams(AtmosphereFramework.java:1306)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:859)
	... 36 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:245)
	... 39 more
Caused by: java.lang.NoSuchMethodError: org.eclipse.jetty.websocket.server.WebSocketServerFactory.<init>(Lorg/eclipse/jetty/websocket/api/WebSocketPolicy;)V
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket$1.<init>(Jetty9AsyncSupportWithWebSocket.java:107)
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.<init>(Jetty9AsyncSupportWithWebSocket.java:107)
	... 44 more```

**Comment by jfarcand** [comment]
Same as #2242
