### ISSUE TITLE
NotSerializableException on AtmosphereResourceImpl

### ISSUE THREAD

**Issue by khauser** [Atmosphere/atmosphere#2249]
I'm trying to serialize the AtmosphereResource within my Vaadin session but i get the following error stacktrace:
```
2017-02-18 17:02:26.748 ERROR 7788 --- [p-nio-80-exec-5] o.a.c.c.C.[.[.[/].[springVaadinServlet]  : Servlet.service() for servlet [springVaadinServlet] in context with path [] threw exception

org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.atmosphere.cpr.AtmosphereResourceImpl
	- field (class "org.codehaus.jackson.map.JsonMappingException$Reference", name: "_from", type: "class java.lang.Object")
	- object (class "org.codehaus.jackson.map.JsonMappingException$Reference", org.atmosphere.cpr.AtmosphereResourceImpl["response"])
	- custom writeObject data (class "java.util.LinkedList")
	- object (class "java.util.LinkedList", [org.atmosphere.cpr.AtmosphereResourceImpl["response"], org.atmosphere.cpr.AtmosphereResponse["response"], com.vaadin.server.VaadinServletResponse["response"], org.springframework.session.web.http.MultiSessionHttpServletResponse["response"], org.springframework.session.web.http.SessionRepositoryResponseWrapper["response"], org.apache.catalina.connector.ResponseFacade["outputStream"], org.apache.catalina.connector.CoyoteOutputStream["ready"]])
	- field (class "org.codehaus.jackson.map.JsonMappingException", name: "_path", type: "class java.util.LinkedList")
	- object (class "org.codehaus.jackson.map.JsonMappingException", org.codehaus.jackson.map.JsonMappingException: It is invalid to call isReady() when the response has not been put into non-blocking mode (through reference chain: org.atmosphere.cpr.AtmosphereResourceImpl["response"]->org.atmosphere.cpr.AtmosphereResponse["response"]->com.vaadin.server.VaadinServletResponse["response"]->org.springframework.session.web.http.MultiSessionHttpServletResponse["response"]->org.springframework.session.web.http.SessionRepositoryResponseWrapper["response"]->org.apache.catalina.connector.ResponseFacade["outputStream"]->org.apache.catalina.connector.CoyoteOutputStream["ready"]))
	- field (class "java.lang.Throwable", name: "cause", type: "class java.lang.Throwable")
	- custom writeObject data (class "java.lang.Throwable")
	- object (class "org.atmosphere.gwt20.server.SerializationException", org.atmosphere.gwt20.server.SerializationException: Failed to serialize data)
	- field (class "java.lang.Throwable", name: "cause", type: "class java.lang.Throwable")
	- custom writeObject data (class "java.lang.Throwable")
	- root object (class "java.io.IOException", java.io.IOException: unexpected exception type)
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:92) ~[spring-data-redis-1.8.0.RELEASE.jar:na]
	at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:171) ~[spring-data-redis-1.8.0.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:129) ~[spring-data-redis-1.8.0.RELEASE.jar:na]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:86) ~[spring-data-redis-1.8.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.saveDelta(RedisOperationsSessionRepository.java:778) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.access$000(RedisOperationsSessionRepository.java:670) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:388) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:245) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:245) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:217) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:170) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80) ~[spring-session-1.3.0.RELEASE.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_66]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_66]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.atmosphere.cpr.AtmosphereResourceImpl
	- field (class "org.codehaus.jackson.map.JsonMappingException$Reference", name: "_from", type: "class java.lang.Object")
	- object (class "org.codehaus.jackson.map.JsonMappingException$Reference", org.atmosphere.cpr.AtmosphereResourceImpl["response"])
	- custom writeObject data (class "java.util.LinkedList")
	- object (class "java.util.LinkedList", [org.atmosphere.cpr.AtmosphereResourceImpl["response"], org.atmosphere.cpr.AtmosphereResponse["response"], com.vaadin.server.VaadinServletResponse["response"], org.springframework.session.web.http.MultiSessionHttpServletResponse["response"], org.springframework.session.web.http.SessionRepositoryResponseWrapper["response"], org.apache.catalina.connector.ResponseFacade["outputStream"], org.apache.catalina.connector.CoyoteOutputStream["ready"]])
	- field (class "org.codehaus.jackson.map.JsonMappingException", name: "_path", type: "class java.util.LinkedList")
	- object (class "org.codehaus.jackson.map.JsonMappingException", org.codehaus.jackson.map.JsonMappingException: It is invalid to call isReady() when the response has not been put into non-blocking mode (through reference chain: org.atmosphere.cpr.AtmosphereResourceImpl["response"]->org.atmosphere.cpr.AtmosphereResponse["response"]->com.vaadin.server.VaadinServletResponse["response"]->org.springframework.session.web.http.MultiSessionHttpServletResponse["response"]->org.springframework.session.web.http.SessionRepositoryResponseWrapper["response"]->org.apache.catalina.connector.ResponseFacade["outputStream"]->org.apache.catalina.connector.CoyoteOutputStream["ready"]))
	- field (class "java.lang.Throwable", name: "cause", type: "class java.lang.Throwable")
	- custom writeObject data (class "java.lang.Throwable")
	- object (class "org.atmosphere.gwt20.server.SerializationException", org.atmosphere.gwt20.server.SerializationException: Failed to serialize data)
	- field (class "java.lang.Throwable", name: "cause", type: "class java.lang.Throwable")
	- custom writeObject data (class "java.lang.Throwable")
	- root object (class "java.io.IOException", java.io.IOException: unexpected exception type)
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:68) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:35) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:90) ~[spring-data-redis-1.8.0.RELEASE.jar:na]
	... 33 common frames omitted
Caused by: java.io.NotSerializableException: org.atmosphere.cpr.AtmosphereResourceImpl
	- field (class "org.codehaus.jackson.map.JsonMappingException$Reference", name: "_from", type: "class java.lang.Object")
	- object (class "org.codehaus.jackson.map.JsonMappingException$Reference", org.atmosphere.cpr.AtmosphereResourceImpl["response"])
	- custom writeObject data (class "java.util.LinkedList")
	- object (class "java.util.LinkedList", [org.atmosphere.cpr.AtmosphereResourceImpl["response"], org.atmosphere.cpr.AtmosphereResponse["response"], com.vaadin.server.VaadinServletResponse["response"], org.springframework.session.web.http.MultiSessionHttpServletResponse["response"], org.springframework.session.web.http.SessionRepositoryResponseWrapper["response"], org.apache.catalina.connector.ResponseFacade["outputStream"], org.apache.catalina.connector.CoyoteOutputStream["ready"]])
	- field (class "org.codehaus.jackson.map.JsonMappingException", name: "_path", type: "class java.util.LinkedList")
	- object (class "org.codehaus.jackson.map.JsonMappingException", org.codehaus.jackson.map.JsonMappingException: It is invalid to call isReady() when the response has not been put into non-blocking mode (through reference chain: org.atmosphere.cpr.AtmosphereResourceImpl["response"]->org.atmosphere.cpr.AtmosphereResponse["response"]->com.vaadin.server.VaadinServletResponse["response"]->org.springframework.session.web.http.MultiSessionHttpServletResponse["response"]->org.springframework.session.web.http.SessionRepositoryResponseWrapper["response"]->org.apache.catalina.connector.ResponseFacade["outputStream"]->org.apache.catalina.connector.CoyoteOutputStream["ready"]))
	- field (class "java.lang.Throwable", name: "cause", type: "class java.lang.Throwable")
	- custom writeObject data (class "java.lang.Throwable")
	- object (class "org.atmosphere.gwt20.server.SerializationException", org.atmosphere.gwt20.server.SerializationException: Failed to serialize data)
	- field (class "java.lang.Throwable", name: "cause", type: "class java.lang.Throwable")
	- custom writeObject data (class "java.lang.Throwable")
	- root object (class "java.io.IOException", java.io.IOException: unexpected exception type)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject(Unknown Source) ~[na:1.8.0_66]
	at java.util.LinkedList.writeObject(Unknown Source) ~[na:1.8.0_66]
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source) ~[na:1.8.0_66]
	at java.lang.Throwable.writeObject(Unknown Source) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source) ~[na:1.8.0_66]
	at java.lang.Throwable.writeObject(Unknown Source) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeFatalException(Unknown Source) ~[na:1.8.0_66]
	at java.io.ObjectOutputStream.writeObject(Unknown Source) ~[na:1.8.0_66]
	at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:63) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	... 35 common frames omitted
```
Here is a showcase project: https://github.com/khauser/vaadin-spring-session-push-showcase

Till now I was not able to get rid of the `NotSerializableException` using a lot of `Serializable`'s in your code (see the feature/MakeItSerializable).
To you have another approach how I could reach my goal to Serialize the AtmosphereResource?

**Comment by jfarcand** [comment]
@khauser I guest adding the interface to the `AtmosphereResourceImpl` might do the trick. Just fork the workspace, add it and let me know if that work => do a pull request and I will cut a `2.4.10` with the fix.

**Comment by jfarcand** [comment]
One workaround is to serialize the `AtmosphereResouce#uuid` and retrieve the real object using the `AtmosphereResourceFactory`when deserializing

**Comment by khauser** [comment]
Thanks for your answer. I also thought that it would be just adding the interface. But no it's not.. the dependency graph has it's depth: https://github.com/khauser/vaadin-spring-session-push-showcase/tree/feature/MakeItSerializable/src/main/java/org/atmosphere/cpr

My way of pain was to first (after adding the `Serializable` interface where possible) apply the _atmosphere-spring_ package to have the `atmosphereFramwork`-bean accessible from within the `AtmophereResource` during it's deserialization. Then I thought about re-adding the unserializable Objects (like AtmosphereConfig, Broadcaster, AsyncSupport, ..) which also could be found under the atmosphereFramwork-bean.

So far so good, here's the code which is called during deserialization:
```
    private void readObject(ObjectInputStream stream)
            throws IOException, ClassNotFoundException {
        stream.defaultReadObject();

        VaadinServletService service = (VaadinServletService)UI.getCurrent().getSession().getService();
        //TODO: if deserialization would work I should use req.getServletContext()
        AtmosphereFramework atmosphere = (AtmosphereFramework)WebApplicationContextUtils.getWebApplicationContext(service.getServlet().getServletContext()).getBean("atmosphereFramework");
        config = atmosphere.getAtmosphereConfig();
        asyncSupport = atmosphere.getAsyncSupport();
        atmosphereHandler = atmosphere.getAtmosphereHandlers().values().iterator().next().atmosphereHandler;

        this.broadcasters = new CopyOnWriteArrayList<Broadcaster>();
        Broadcaster baseBroadCaster = atmosphere.getBroadcasterFactory().lookupAll().iterator().next();
        baseBroadCaster.addAtmosphereResource(this);
        this.setBroadcaster(baseBroadCaster);
    }
```
Deserialization works with that when I make `AtmosphereRequest req` transient, but if not, it fails.

Since it needed to get all work (or to get nearer) I also need to get the dependent `AtmosphereRequest` deserialized. I tried to, but I still get an error:

```
Exception in thread "Thread-8" org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: org.atmosphere.cpr.AtmosphereRequestImpl; no valid constructor
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:81)
	at org.springframework.data.redis.core.AbstractOperations.deserializeValue(AbstractOperations.java:318)
	at org.springframework.data.redis.core.AbstractOperations$ValueDeserializingRedisCallback.doInRedis(AbstractOperations.java:58)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:207)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:169)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:91)
	at org.springframework.data.redis.core.DefaultValueOperations.get(DefaultValueOperations.java:43)
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:181)
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:160)
	at com.vaadin.ui.UI.push(UI.java:1594)
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1009)
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1851)
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1817)
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1392)
	at com.vaadin.ui.UI.access(UI.java:1487)
	at com.example.VaadinUI$FeederThread.run(VaadinUI.java:42)
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.InvalidClassException: org.atmosphere.cpr.AtmosphereRequestImpl; no valid constructor
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78)
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36)
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:79)
	... 15 more
Caused by: java.io.InvalidClassException: org.atmosphere.cpr.AtmosphereRequestImpl; no valid constructor
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(Unknown Source)
	at java.io.ObjectStreamClass.checkDeserialize(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.defaultReadObject(Unknown Source)
	at org.atmosphere.cpr.AtmosphereResourceImpl.readObject(AtmosphereResourceImpl.java:1037)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70)
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73)
	... 17 more
```

Maybe you have an idea how to come over that? If we would be able to get this work in an acceptable way, I also would add a pull-request to your repo. But for now it's just testing.

**Comment by khauser** [comment]
I guess serializing the Request or even the AtmosphereResource is a bad idea. Instead the connection should be reestablished and a new AtmosphereResource should be send. I think that way it's also meant in the vaadin code: 

>     /**
     * Reinitializes this PushConnection after deserialization. The connection
     * is initially in disconnected state; the client will handle the
     * reconnecting.
     */
    private void readObject(ObjectInputStream stream)
            throws IOException, ClassNotFoundException {
        stream.defaultReadObject();
        state = State.DISCONNECTED;
    }

So I now need to find out why the client isn't reconnecting... But thanks for your help
