### ISSUE TITLE
Automatic close of Websocket connections by tomcat

### ISSUE THREAD

**Issue by maddaliravi** [Atmosphere/atmosphere#2250]
Hi , i am using gwt web sockets of atmosphere framework on tomcat , we use this for broadcasting a message from server to all clients (browsers) to cascade any important information . so the usage of web socket connection is very minimal and most of the time web socket connection is idle. 
I notice that tomcat is closing the web socket connections frequently. Refer to the logs below.

Though the default Heartbeat interceptor is kept as it is . ie., server heart beat at 60 seconds and client heartbeat is 0 seconds (default disabled) the behavior remains same (ie., tomcat closing web socket connections).
and i can see another attribute called 'max idle time' in atmosphere config which is defaulted to 5 mins , so we changed it to 30 mins. but still this issue is happening but with less frequency.

So i have the following questions.

-> Does this 'maxIdleTime' have impact on tomcat to close web socket connections ?

-> As i said initially , in my application most of the time web socket is idle due to its usage as a channel by server only to cascade important information. Assume it can be used once in a day or a week or a month... So How to make the web socket alive until user close the browser or logout or session timeout  with out any activity (or) very less activity happening  on the web socket connection.

-> In the hear beat interceptor , what happens if i turn off server heart beat (disable) and turn on client heart beat (for ex: every 60 seconds) ? . i understand that server heart beat is to ensure that web socket is active and to escape from proxy servers.  but the same can be achieved by client heartbeat also ? 

-> What additional advantage by activating client heartbeat ? i mean .. by setting this can we ensure we does not reach the 'MaxIdleTime' of a web socket ?. does this client heartbeat have any performance impact.

Thank you to respond.

logs
-----------------------------------------------
n>2017-02-24 11:26:05,035 [thread-1] TRACE osphere.container.TomcatWebSocketHandler - onClose 1000
n>2017-02-24 11:26:05,035 [thread-1] TRACE bsocket.WebSocketStreamingHandlerAdapter - onClose org.apache.catalina.websocket.WsOutbound@645508b0
n>2017-02-24 11:26:05,036 [thread-1] TRACE here.websocket.DefaultWebSocketProcessor - About to close AtmosphereResource for AtmosphereResource{
         uuid=03563bd9-975b-4ba0-ba40-c72e30b4c878,
         transport=WEBSOCKET,
         isInScope=true,
         isResumed=false,
         isCancelled=false,
         isSuspended=true,
         broadcasters=/stream,
         isClosedByClient=false,
         isClosedByApplication=false,
         action=Action{timeout=-1, type=SUSPEND}} with code 1000
n>2017-02-24 11:26:05,036 [thread-1] TRACE org.atmosphere.cpr.AsynchronousProcessor - Finishing lifecycle for AtmosphereResource 03563bd9-975b-4ba0-ba40-c72e30b4c878
n>2017-02-24 11:26:05,037 [thread-1] TRACE ndler.AbstractReflectorAtmosphereHandler - Message was null for AtmosphereEvent AtmosphereResourceEventImpl{ isCancelled=true isClosedByClient=false isClosedByApplication=false isResumedOnTimeout=false throwable=null resource=null}
n>2017-02-24 11:26:05,037 [thread-1] TRACE rg.atmosphere.cpr.AtmosphereResourceImpl - Invoking listener [org.atmosphere.interceptor.HeartbeatInterceptor$2@3e5d602c, .server.alert.WebSocketStream$1@6acc8d96] for 03563bd9-975b-4ba0-ba40-c72e30b4c878
n>2017-02-24 11:26:05,037 [thread-1] INFO server.alert.WebSocketStream - Browser {} unexpectedly disconnected
n>2017-02-24 11:26:05,037 [thread-1] TRACE .websocket.WebSocketEventListenerAdapter - WebSocketEvent{message='1005', type=CLOSE, webSocket=org.apache.catalina.websocket.WsOutbound@645508b0}
n>2017-02-24 11:26:05,037 [thread-1] TRACE rg.atmosphere.cpr.AtmosphereResourceImpl - Cancelling 03563bd9-975b-4ba0-ba40-c72e30b4c878
n>2017-02-24 11:26:05,037 [thread-1] TRACE    org.atmosphere.cpr.DefaultBroadcaster - Removing AtmosphereResource 03563bd9-975b-4ba0-ba40-c72e30b4c878 for Broadcaster /stream
n>2017-02-24 11:26:05,038 [thread-1] TRACE org.atmosphere.cpr.SessionTimeoutSupport -
java.lang.IllegalStateException: getAttribute: Session already invalidated
 at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1165) ~[catalina.jar:7.0.35]
        at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:122) ~[catalina.jar:7.0.35]
        at org.atmosphere.cpr.SessionTimeoutSupport.get(SessionTimeoutSupport.java:73) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.cpr.SessionTimeoutSupport.restoreTimeout(SessionTimeoutSupport.java:59) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.cpr.SessionTimeoutSupport.restoreTimeout(SessionTimeoutSupport.java:69) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:817) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:505) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.cpr.AsynchronousProcessor.endRequest(AsynchronousProcessor.java:597) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.websocket.DefaultWebSocketProcessor.executeClose(DefaultWebSocketProcessor.java:705) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.websocket.DefaultWebSocketProcessor.close(DefaultWebSocketProcessor.java:653) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.atmosphere.container.TomcatWebSocketHandler.onClose(TomcatWebSocketHandler.java:84) [atmosphere-runtime-2.4.6.jar:2.4.6]
        at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:215) [catalina.jar:7.0.35]
        at org.apache.catalina.websocket.StreamInbound.closeOutboundConnection(StreamInbound.java:205) [catalina.jar:7.0.35]
        at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:136) [catalina.jar:7.0.35]
        at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83) [tomcat-coyote.jar:7.0.35]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587) [tomcat-coyote.jar:7.0.35]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310) [tomcat-coyote.jar:7.0.35]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
-----------------------------------------------

**Comment by amrfaissal** [comment]
I am having the same problem. Any updates on this issue?

**Comment by saikiran939** [comment]
if you are using IdleResourceInterceptor did you try increasing ApplicationConfig.MAX_INACTIVE ?

Does this 'maxIdleTime' have impact on tomcat to close web socket connections ?
Answer: Same as this: http://docs.oracle.com/javaee/7/api/javax/websocket/Session.html#setMaxIdleTimeout-long-

-> In the hear beat interceptor , what happens if i turn off server heart beat (disable) and turn on client heart beat (for ex: every 60 seconds) ? . i understand that server heart beat is to ensure that web socket is active and to escape from proxy servers. but the same can be achieved by client heartbeat also ?

There are two sides of the coin:

1. To keep the connection open by sending some messages through the proxy so that it will not be closed - this is acheived by server heartbeat
2. There are usecases where you need to know whether client is connected or not - this is acheived by client side heartbeat

-> What additional advantage by activating client heartbeat ? i mean .. by setting this can we ensure we does not reach the 'MaxIdleTime' of a web socket ?. does this client heartbeat have any performance impact.

Asnwer: There should be no performance impact - if the client is logged in from a websocket supported browser from mobile it may charge client very minute 'data' cost - the heartbeat text is 'X' so only one byte of data is sent.

**Comment by maddaliravi** [comment]
Hi sai , thank you for the reply.

I am keeping default interceptors that comes with Atmosphere ... so IdleResourceInterceptor will be active in my application.

but how is this MAX_INACTIVE is different from maxIdleTime parameter ?

As i mentioned earlier , my requirement is to use the web-socket for broadcasting important alerts to all clients or browsers from server... so mostly the web-socket connection will be idle for a long long time... but i wanted it to be alive though...  for ex: even though if a client is using the application .. unless some message comes from server, web-socket connection is not used... our aim is to keep this connection alive .. probably hours together.. but we should be able to close them once the user closes the browser , log out etc., thanks to advice.

**Comment by maddaliravi** [comment]
we find that to set 'maxIdleTime' attribute of atmosphere framework to a very high value ..lets say.. equivalent of 8 to 9 hours.
