### ISSUE TITLE
ConcurrentModificationException in org.atmosphere.cpr.AtmosphereRequestImpl.getAttributeNames

### ISSUE THREAD

**Issue by zanzan23** [Atmosphere/atmosphere#2277]
Hi, I’m facing with a problem using Atmosphere 2.4.8 with GWT (extensions version 2.4.3) on wildfly 10.1.0 that seems to be a duplicate of https://github.com/Atmosphere/atmosphere/issues/2062. It happens randomly and I was not able to reproduce it easily.
BTW looking at the code of the class AtmosphereRequestImpl I found out that the methods removeAttribute and getAttributeNames can start from different thread on the same resource and this can generate the ConcurrentModificationException. I inserted a ReentrantReadWriteLock and synchronize these methods on this lock and the problem does not occur anymore. Do I miss something?

This is the call stack of the exception:

2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) Exception in thread "default task-4" java.lang.RuntimeException: java.util.ConcurrentModificationException
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.ServletContextImpl.invokeRunnable(ServletContextImpl.java:902)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl.onAsyncComplete(AsyncContextImpl.java:576)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl.access$100(AsyncContextImpl.java:68)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl$3.run(AsyncContextImpl.java:312)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl$6.run(AsyncContextImpl.java:455)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:566)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-06-27 19:18:03,400 ERROR [stderr] (default task-4) 	at java.lang.Thread.run(Thread.java:745)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) Caused by: java.util.ConcurrentModificationException
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.util.IteratorEnumeration.nextElement(IteratorEnumeration.java:44)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at java.util.Collections.list(Collections.java:5240)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.atmosphere.cpr.AtmosphereRequestImpl.getAttributeNames(AtmosphereRequestImpl.java:895)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.context.beanstore.http.RequestBeanStore.getAttributeNames(RequestBeanStore.java:47)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.context.beanstore.AttributeBeanStore.getPrefixedAttributeNames(AttributeBeanStore.java:239)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.context.beanstore.AttributeBeanStore.fetchUninitializedAttributes(AttributeBeanStore.java:120)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.context.beanstore.AttributeBeanStore.attach(AttributeBeanStore.java:107)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.context.http.HttpRequestContextImpl.associate(HttpRequestContextImpl.java:64)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.context.http.HttpRequestContextImpl.associate(HttpRequestContextImpl.java:40)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.servlet.HttpContextLifecycle.requestInitialized(HttpContextLifecycle.java:236)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at org.jboss.weld.servlet.WeldInitialListener.requestInitialized(WeldInitialListener.java:152)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.core.ApplicationListeners.requestInitialized(ApplicationListeners.java:246)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl.setupRequestContext(AsyncContextImpl.java:660)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl.access$700(AsyncContextImpl.java:68)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.AsyncContextImpl$7.run(AsyncContextImpl.java:581)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.ServletContextImpl$2.call(ServletContextImpl.java:154)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.ServletContextImpl$2.call(ServletContextImpl.java:151)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	at io.undertow.servlet.spec.ServletContextImpl.invokeRunnable(ServletContextImpl.java:900)
2017-06-27 19:18:03,401 ERROR [stderr] (default task-4) 	... 8 more

**Comment by jfarcand** [comment]
@zanzan23 That's an issue. Pull request welcomed :-)

**Comment by zanzan23** [comment]
Ok, I'll do it. :-)

**Comment by saikiran939** [comment]
Here `org.atmosphere.cpr.AtmosphereRequestImpl.Builder.localAttributes` operates on ConcurrentHashMap so exception should not have originated from here. 

Exception should have happened from here but I'm not really sure `b.request.removeAttribute(name);`

**Comment by zanzan23** [comment]
The exception is not from localAttributes but from Collections.list(b.request.getAttributeNames()) 
invoked from one thread while another thread executes b.request.removeAttribute(name);

**Comment by saikiran939** [comment]
Thanks for clarifying, I could not understand fully from the above stacktraces.

**Comment by orange-buffalo** [comment]
@zanzan23 have you had any chance to prepare a pull request for this?

**Comment by zanzan23** [comment]
Unfortunately no, sorry, I’m just going out from a very stressing time. BTW I should have the chance to prepare the pull request in the next few days.

Da: Bogdan Ilchyshyn [mailto:notifications@github.com]
Inviato: mercoledì 13 dicembre 2017 07:14
A: Atmosphere/atmosphere
Cc: Zanatta Fabio; Mention
Oggetto: Re: [Atmosphere/atmosphere] ConcurrentModificationException in org.atmosphere.cpr.AtmosphereRequestImpl.getAttributeNames (#2277)


@zanzan23<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzanzan23&data=02%7C01%7Cfabio.zanatta%40p-a.it%7C769578d779a84fbf823908d541f0c5d3%7C2ed09193c3544bd9a4d7b7c11168f696%7C0%7C0%7C636487424733537684&sdata=ST4KA%2BTnwNHmq8cs2myMJW2EXkevinpTANo3OIeNa0g%3D&reserved=0> have you had any chance to prepare a pull request for this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAtmosphere%2Fatmosphere%2Fissues%2F2277%23issuecomment-351293936&data=02%7C01%7Cfabio.zanatta%40p-a.it%7C769578d779a84fbf823908d541f0c5d3%7C2ed09193c3544bd9a4d7b7c11168f696%7C0%7C0%7C636487424733537684&sdata=mlQNtZB0cfSaFaQeWRbUyeUebLevTw7XlpNFhBdYJKY%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAcW0s6IFEgjuBBXniEZ9Yv_zX2nszywzks5s_2tFgaJpZM4OG8TZ&data=02%7C01%7Cfabio.zanatta%40p-a.it%7C769578d779a84fbf823908d541f0c5d3%7C2ed09193c3544bd9a4d7b7c11168f696%7C0%7C0%7C636487424733537684&sdata=RUw87QSIRgRWOqP65i0zS82QzAXPRGlA2ltJfDP3I5I%3D&reserved=0>.

I dati contenuti nella presente e-mail sono confidenziali e riservati al destinatario. Nel caso in cui la presente sia stata per qualunque ragione inviata ad un destinatario errato, si prega di segnalare l’errore al mittente e di distruggere contestualmente il contenuto della comunicazione ed ogni eventuale file allegato. This message and its attachments are for the designated recipient only and may contain privileged or confidential information. If you receive it in error, please notify the sender immediately and delete the original. Any other use of the email is prohibited.

**Comment by orange-buffalo** [comment]
@jfarcand as the issue is closed, could you please advise which version includes the fix?

**Comment by jfarcand** [comment]
@orange-buffalo 2.4.19+
