### ISSUE TITLE
Error in handling big volume of data

### ISSUE THREAD

**Issue by mohsenasadi** [Atmosphere/atmosphere#2301]
Hello,

I am using atmosphere for streaming data from tomcat server to client side written in javascript and developed a weksocket channel which implements WebSocketStreamingHandlerAdapter. I am sending many messages around 10000 message and the message is similar to this: 
{"eventName":"bubleLayer","message":{"SHAPE":"POINT (-12048311.6244 5329789.155)","geoType":"POINT","TIMESTAMP":"2015-08-05 23:49:23.0","ID":"43.11694574","VALUE":37.02476501464844}}

The problem is that when I test the framework on my localhost all 10000 messages are pushed to my clientside, however, we I remotely access to application after pushing around 5000 message, it get this error:
java.io.IOException: Socket closed
	at org.atmosphere.container.version.JSR356WebSocket.write(JSR356WebSocket.java:75)
	at StreamQueryService.pushResultToSocket(StreamQueryService.java:123)
	at StreamQueryService.processResultSet(StreamQueryService.java:107)
	at StreamQueryService.runFirstLoad(StreamQueryService.java:96)
	at StreamQueryService.handleStreamingQuery(StreamQueryService.java:66)
	at websocket.StreamingModelChannel$1.onMessage(StreamingModelChannel.java:61)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.notifyListener(DefaultWebSocketProcessor.java:747)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:470)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:246)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:243)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

then couple of more messages are pushed and then I see this error:

00:22:24.306 [http-nio-8080-exec-4] DEBUG o.a.w.DefaultWebSocketProcessor - Listener error {}
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1224) ~[tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.textStart(WsRemoteEndpointImplBase.java:1187) ~[tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendStringByCompletion(WsRemoteEndpointImplBase.java:209) ~[tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsRemoteEndpointAsync.sendText(WsRemoteEndpointAsync.java:47) ~[tomcat-websocket.jar:8.5.20]
	at org.atmosphere.container.version.JSR356WebSocket.write(JSR356WebSocket.java:73) ~[atmosphere-runtime-2.4.2.jar:2.4.2]
	at StreamQueryService.pushResultToSocket(StreamQueryService.java:123) ~[classes/:na]
	at StreamQueryService.processResultSet(StreamQueryService.java:107) ~[classes/:na]
	at StreamQueryService.runFirstLoad(StreamQueryService.java:96) ~[classes/:na]
	at StreamQueryService.handleStreamingQuery(StreamQueryService.java:66) ~[classes/:na]
	at com.twc.streaming.websocket.StreamingModelChannel$1.onMessage(StreamingModelChannel.java:61) ~[classes/:na]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.notifyListener(DefaultWebSocketProcessor.java:747) [atmosphere-runtime-2.4.2.jar:2.4.2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:470) [atmosphere-runtime-2.4.2.jar:2.4.2]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:246) [atmosphere-runtime-2.4.2.jar:2.4.2]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:243) [atmosphere-runtime-2.4.2.jar:2.4.2]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-websocket.jar:8.5.20]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-coyote.jar:8.5.20]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-coyote.jar:8.5.20]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:8.5.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457) [tomcat-coyote.jar:8.5.20]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by jfarcand** [comment]
@mohsenasadi Have you found a solution? It seems to be a bug in Tomcat, not in Atmosphere IMO
