### ISSUE TITLE
The path [/{path0}/] contains one or more empty segments - when registering endpoints - after upgrade to 2.4.21

### ISSUE THREAD

**Issue by kkolinko** [Atmosphere/atmosphere#2320]
There is a bug in commit performed by pull request #2316. In 14367ba, to be specific.

Configuration:  Tomcat 8.5.29, Vaadin Framework 8.4-SNAPSHOT, uses atmosphere-runtime-2.4.21.vaadin1.jar.

VaadinServlet is mapped in web.xml as
```
  <servlet>
    <servlet-name>Application</servlet-name>
    <servlet-class>com.vaadin.server.VaadinServlet</servlet-class>
    <init-param> ...
    <async-supported>true</async-supported>
  </servlet>
  <servlet-mapping>
    <servlet-name>Application</servlet-name>
    <url-pattern>/*</url-pattern>
    <url-pattern>/VAADIN/*</url-pattern>
  </servlet-mapping>
```
I observe the following failure when web application starts.
```
Apr 03, 2018 11:35:11 AM org.atmosphere.cpr.DefaultAsyncSupportResolver newCometSupport
SEVERE: Real error: The path [/{path0}/] contains one or more empty segments which are is not permitted
java.lang.IllegalArgumentException: The path [/{path0}/] contains one or more empty segments which are is not permitted
	at org.apache.tomcat.websocket.server.UriTemplate.<init>(UriTemplate.java:71)
	at org.apache.tomcat.websocket.server.WsServerContainer.addEndpoint(WsServerContainer.java:155)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:99)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2085)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212)
	at com.vaadin.server.communication.JSR356WebsocketInitializer.initAtmosphereForVaadinServlet(JSR356WebsocketInitializer.java:152)
	at com.vaadin.server.communication.JSR356WebsocketInitializer.contextInitialized(JSR356WebsocketInitializer.java:118)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4753)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Comments on lines 73-39 in 14367ba say that the commit registers the following endpoints:
```
        // Register endpoints at
        // /servletPath
        // /servletPath/
        // /servletPath/{path1}
        // /servletPath/{path1}/
        // /servletPath/{path1}/{path2}
        // etc with up to `pathLength` parameters 
```

If you look into source code of Tomcat's UriTemplate you will see that it rejects templates that end with '/' and have parameters. That is because such templates cannot be used for uri matching.

See comments in the source code. Exception is thrown from line 71:
http://svn.apache.org/viewvc/tomcat/tc8.5.x/tags/TOMCAT_8_5_29/java/org/apache/tomcat/websocket/server/UriTemplate.java?view=markup#l63

I think that the solution is to register the following endpoint:
```
        // /servletPath/{path1}
```
but do NOT register the following one:
```
        // /servletPath/{path1}/
```

----

This issue may be related with #2317.

I thought that it may be the root cause behind it (#2317 lacks details to be sure), but I see that in my case it is not fatal. There is no '404'. The web application continues starting and runs successfully.

I see that the exception is caught in DefaultAsyncSupportResolver.newCometSupport() and consumed,
and the framework switches over to implementation based on Servlet 3.0 Async API:
```
...
Apr 03, 2018 12:41:17 PM org.atmosphere.cpr.AtmosphereFramework info
INFO: Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running under container: Apache Tomcat/8.5.29 using javax.servlet/3.0
```
So this issue is not fatal for me.

----

An old issue #1508 has an idea of a configuration workaround, but I am not sure how it could be applied here. My attempt to apply one failed.

**Comment by kkolinko** [comment]
> In 14367ba, to be specific.

The above is the hash of this commit in **master** branch. In **atmosphere-2.4.x** (2.4.21) that I am using it is d3b6761.

**Comment by jfarcand** [comment]
@kkolinko Can you try the latest snapshot (2.4.23-SNAPSHOT). Thanks for the detailed analysis!!!!!!

**Comment by kkolinko** [comment]
Re: 7670c36 
1. Line 83 is a bug. It is
```
endpointPaths.add("/");
```
I think that it has to be
```
endpointPaths.add(servletPath + '/');
```
2. Comments above the code were not updated. Remove the following line (76):
```
// /servletPath/{path1}/
```
and replace {path1} -> {path0} in the comments (lines 75-77, and also 92), as cycle start numbering with i=0.

----
(Reading WebSocket 1.1 specification - chapter "3.1.1 URI Mapping",
I think that declaring an explicit "/servletPath/" pattern in the case when (pathLength > 0) is excessive, but not an error.  It will be matched by "/servletPath/{path0}" as well. Exact URIs have precedence over templates, they do not conflict with each other.)

----
> Can you try the latest snapshot (2.4.23-SNAPSHOT).

OK, I will look for that. - I am using vaadin fork of this library. I see what patches they have applied (in their fork of this repository), but I have never built it myself yet.

**Comment by jfarcand** [comment]
Rolled back to the previous implementation as it cause too many regression
