### ISSUE TITLE
Issue with tomcat 9 and atmosphere 2.2

### ISSUE THREAD

**Issue by mohitbhindwal** [Atmosphere/atmosphere#2333]
I am getting this in tomcat logs while tries to connect with web socket of application.
With tomcat 9 is it compulsory to have atmosphere 2.4 ?
With tomcat 9 Do i have to use cometd only or I can use websocket,long pull ?
Do I need to upgrade api for tomcat 9 ?

 java.lang.NullPointerException
    at org.eclipse.jetty.websocket.WebSocketFactory.upgrade(WebSocketFactory.java:238)
    at org.eclipse.jetty.websocket.WebSocketFactory.acceptWebSocket(WebSocketFactory.java:396)
    at org.atmosphere.container.JettyWebSocketUtil.doService(JettyWebSocketUtil.java:60)
    at org.atmosphere.container.JettyAsyncSupportWithWebSocket.service(JettyAsyncSupportWithWebSocket.java:66)
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2013)
    at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:190)
    at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:176)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by jfarcand** [comment]
Remove Jetty from you classpath
