### ISSUE TITLE
IllegalStateException in dirty closing of resource

### ISSUE THREAD

**Issue by saikiran939** [Atmosphere/atmosphere#2340]
Hi, 

We've been seeing this exception in logs for some time. This happens only when a resource is identified as duplicate and it tries to close the async context by fetching from request object, looks like atmosphere is holding a stale http request object.

I tried to fix this in atmosphere code by catching the exception in `AtmosphereRequestImpl.attributeWithoutException()` which is alreaddy catching NPE but the return type in case of NPE is empty string, but the return type here is Object - meaning attribute value could be of any type. May be this was to fix a particular use-case, in this dirty close scenario returning null or empty empty string could be lead to other runtime cast errors. 

The only other to fix is in: `org.atmosphere.container.Servlet30CometSupport.endAsyncContext(AtmosphereRequest)` by catching IllegalStateException when do `request.getAttribute(FrameworkConfig.ASYNC_CONTEXT);`

If the fix is OK i can submit a PR.

`2018-04-30 16:39:53,731 [tp-apr-8080-exec-171] [          ] [                    ] [                    ] (here.cpr.AsynchronousProcessor) ERROR   - Interceptor Atmosphere LifeCycle crashed. Processing will continue with other interceptor.
java.lang.IllegalStateException: The request object has been recycled and is no longer associated with this facade
    at org.apache.catalina.connector.RequestFacade.getAttribute(RequestFacade.java:279) ~[catalina.jar:7.0.78]
    at org.atmosphere.cpr.AtmosphereRequestImpl.attributeWithoutException(AtmosphereRequestImpl.java:891) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AtmosphereRequestImpl.getAttribute(AtmosphereRequestImpl.java:652) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.container.Servlet30CometSupport.endAsyncContext(Servlet30CometSupport.java:124) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.container.Servlet30CometSupport.complete(Servlet30CometSupport.java:119) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.container.Servlet30CometSupport.complete(Servlet30CometSupport.java:46) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:806) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AtmosphereResourceImpl.dirtyClose(AtmosphereResourceImpl.java:910) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.DefaultBroadcaster.addAtmosphereResource(DefaultBroadcaster.java:1373) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:401) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor.postInspect(AtmosphereResourceLifecycleInterceptor.java:145) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AsynchronousProcessor.postInterceptors(AsynchronousProcessor.java:374) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:230) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:68) ~[pratmosphere-runtime-2.4.5.2.jar:?]
    at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2209) ~[pratmosphere-runtime-2.4.5.2.jar:?]`

**Comment by jfarcand** [comment]
@saikiran939 +1 for the fix

**Comment by saikiran939** [comment]
Opened PR at https://github.com/Atmosphere/atmosphere/pull/2341
