### ISSUE TITLE
NPE from AtmosphereRequestImpl.getCookies

### ISSUE THREAD

**Issue by meszarv** [Atmosphere/atmosphere#2344]
```log
2018-07-27 00:07:35,086 WARN  [http-nio-8080-exec-17] (DefaultWebSocketProcessor.java:596) Failed invoking AtmosphereFramework.doCometSupport()
java.lang.NullPointerException
        at org.atmosphere.cpr.AtmosphereRequestImpl.getCookies(AtmosphereRequestImpl.java:324)
        at javax.servlet.http.HttpServletRequestWrapper.getCookies(HttpServletRequestWrapper.java:69)
```

Root cause in JSR356Endpoint.java line ~220:
when original request has no "Cookie" header (or in my case if the header is lower case "cookie")
, cookies variable used to build the AtmosphereRequestImpl is never initialized. 
See:
```java
           List<String> cookieHeaders = handshakeHeaders.get("Cookie");
            Set<Cookie> cookies = null;
            if (cookieHeaders != null) {
                cookies = new HashSet<Cookie>();
                for (String cookieHeader : cookieHeaders)
                    cookies.addAll(CookieUtil.ServerCookieDecoder.STRICT.decode(cookieHeader));
            }
```

**Comment by jfarcand** [comment]
@meszarv Pull request welcomed! I will create a new release with it.
