### ISSUE TITLE
NPE on trace client already disconnected received event log.

### ISSUE THREAD

**Issue by dyorgio** [Atmosphere/atmosphere#2354]
Hello, I'm using version 2.4.30 with vaadin, and some times my production log have theses exceptions:

```
2018-10-09 18:01:38.977 ERROR 5 --- [io-8080-exec-79] c.v.s.c.PushAtmosphereHandler            : Exception in push connection

java.lang.NullPointerException: null
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:652) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:630) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:499) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.endRequest(AsynchronousProcessor.java:604) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.executeClose(DefaultWebSocketProcessor.java:710) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.close(DefaultWebSocketProcessor.java:658) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.atmosphere.container.JSR356Endpoint.onClose(JSR356Endpoint.java:310) [atmosphere-runtime-2.4.30.vaadin1.jar!/:2.4.30.vaadin1]
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:535) [tomcat-embed-websocket-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:513) [tomcat-embed-websocket-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:240) [tomcat-embed-websocket-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:162) [tomcat-embed-websocket-8.5.29.jar!/:8.5.29]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar!/:8.5.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```

Looking at source I can found that it is just a log command, but I believe that it need to be handled to support nulls:

```java
// AtmosphereResourceImpl.java:652
logger.trace("Skipping notification, already disconnected {}", event.getResource().uuid());
```

**Comment by jfarcand** [comment]
@dyorgio Pull request welcomed! I will cut a release after that to accommodate you.

**Comment by dyorgio** [comment]
Hi  @jfarcand,  I made it on master, how about include it on 2.4.x?
