### ISSUE TITLE
AtmosphereServlet.wrap() - ConcurrentModificationException

### ISSUE THREAD

**Issue by tbuckel** [Atmosphere/atmosphere#2357]
Hi,

I'm occasionally seeing this exception in my server logs which uses Atmosphere.

```
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
        at java.util.HashMap$KeyIterator.next(HashMap.java:956)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
        at org.apache.catalina.connector.Request.getAttributeNames(Request.java:1040)
        at org.apache.catalina.connector.RequestFacade.getAttributeNames(RequestFacade.java:299)
        at org.atmosphere.cpr.AtmosphereRequest.wrap(AtmosphereRequest.java:1924)
        at org.atmosphere.cpr.AtmosphereServlet.event(AtmosphereServlet.java:264)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilterEvent(ApplicationFilterChain.java:482)
        at org.apache.catalina.core.ApplicationFilterChain.doFilterEvent(ApplicationFilterChain.java:375)
        at org.apache.catalina.core.StandardWrapperValve.event(StandardWrapperValve.java:409)
        at org.apache.catalina.core.StandardContextValve.event(StandardContextValve.java:145)
        at org.apache.catalina.valves.ValveBase.event(ValveBase.java:222)
        at org.apache.catalina.core.StandardHostValve.event(StandardHostValve.java:263)
        at org.apache.catalina.valves.ValveBase.event(ValveBase.java:222)
        at org.apache.catalina.valves.ValveBase.event(ValveBase.java:222)
        at org.apache.catalina.core.StandardEngineValve.event(StandardEngineValve.java:136)
        at org.apache.catalina.connector.CoyoteAdapter.event(CoyoteAdapter.java:212)
        at org.apache.coyote.http11.Http11NioProcessor.event(Http11NioProcessor.java:119)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:614)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1753)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1712)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

I'm using Atmosphere 2.3.2 on Tomcat 7.0.63 proxied by nginx.
Any help would be appreciated.

Thanks,
Thomas

**Comment by jfarcand** [comment]
Try with `2.4.x` or `2.5.x` as this has been fixed.
