### ISSUE TITLE
Error in handling big volume of data and high concurrency

### ISSUE THREAD

**Issue by loveslikey** [Atmosphere/atmosphere#2359]
Hello,
I am using atmosphere for streaming data from spring boot(2.0.3.RELEASE) server to client side written in javascript and developed a websocket channel. When I try to send about 500K size json string many times in multithreading  ,the server  seem block long time,and cannot push any message any more,Although has other threads use  "atmosphereResource.write(data)" to write data. Then server cuase exception and connection is closed. the other connections and  threads recover.
above is exception:
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.atmosphere.config.managed.Invoker.invokeMethod(Invoker.java:49) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.config.managed.ManagedAtmosphereHandler.message(ManagedAtmosphereHandler.java:371) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.config.managed.ManagedAtmosphereHandler.onRequest(ManagedAtmosphereHandler.java:171) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2300) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269) [atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-embed-websocket-8.5.31.jar:8.5.31]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.RuntimeException: java.io.IOException: Socket closed
	at org.atmosphere.cpr.AtmosphereResponseImpl.write(AtmosphereResponseImpl.java:812) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AtmosphereResponseImpl.write(AtmosphereResponseImpl.java:784) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AtmosphereResourceImpl.write(AtmosphereResourceImpl.java:596) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AtmosphereResource$write$1.call(Unknown Source) ~[na:na]
	at com.major.cmano.service.CmanoGisService.transformAndBroadcast(CmanoGisService.groovy:77) ~[classes/:na]
	at com.major.cmano.service.CmanoGisService$transformAndBroadcast$1.callCurrent(Unknown Source) ~[na:na]
	at com.major.cmano.service.CmanoGisService.transformAndBroadcast(CmanoGisService.groovy:201) ~[classes/:na]
	at com.major.cmano.atmosphere.CesiumAtmospHereService.onMessage(CesiumAtmospHereService.java:162) ~[classes/:na]
	... 36 common frames omitted
Caused by: java.io.IOException: Socket closed
	at org.atmosphere.container.version.JSR356WebSocket.write(JSR356WebSocket.java:75) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:255) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:220) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.websocket.WebSocket.write(WebSocket.java:46) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.write(AtmosphereResponseImpl.java:957) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	at org.atmosphere.cpr.AtmosphereResponseImpl.write(AtmosphereResponseImpl.java:803) ~[atmosphere-runtime-2.5.2.jar:2.5.2]
	... 43 common frames omitted

**Comment by loveslikey** [comment]
@jfarcand  I hava tried he latest release version( 2.5.2 and 2.4.32 ),but it still not works.
ps: environment is  JDK8

**Comment by jfarcand** [comment]
` java.lang.RuntimeException: java.io.IOException: Socket closed at ` ... so check win7

**Comment by loveslikey** [comment]
what should I do for checking win7, give me some tips,please.
@jfarcand
