### ISSUE TITLE
No bean named 'org.atmosphere.cpr.AtmosphereConfig' available

### ISSUE THREAD

**Issue by perssonmathias** [Atmosphere/atmosphere#2374]
I recently upgraded to the latest versions of atmosphere-runtime (2.5.4) and atmosphere-spring (2.5.0) and get the following error message in the Tomcat log. Everything was working fine before the upgrade. Any ideas?

```WARNING: Unable to configure injection
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.atmosphere.cpr.AtmosphereConfig' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:687)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1218)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:271)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1098)
        at org.atmosphere.spring.SpringWebObjectFactory.configure(SpringWebObjectFactory.java:90)
        at org.atmosphere.cpr.AtmosphereFramework.lookupDefaultObjectFactoryType(AtmosphereFramework.java:1707)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:880)
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
        at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:75)
        at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:84)
        at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:80)
        at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:75)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:992)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1842)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

And here is the code
```java
@Configuration
public class WebsocketConfig {
    @Bean
    public ServletRegistrationBean atmosphereServlet() {
        ServletRegistrationBean registration = new ServletRegistrationBean(new AtmosphereServlet(), "/server/websocket/*");
        registration.addInitParameter(ApplicationConfig.SCAN_CLASSPATH, "false");
        registration.addInitParameter(ApplicationConfig.ANALYTICS, "false");
        registration.addInitParameter(ApplicationConfig.CLIENT_HEARTBEAT_INTERVAL_IN_SECONDS, "10");
        registration.addInitParameter(ApplicationConfig.WEBSOCKET_MAXTEXTSIZE, "10485760"); // 10mb
        registration.addInitParameter(ApplicationConfig.WEBSOCKET_BUFFER_SIZE, "131072"); // 128kb
        registration.setLoadOnStartup(0);
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE);
        registration.setAsyncSupported(true);
        return registration;
    }
}
```

**Comment by jfarcand** [comment]
@perssonmathias which version were you using before?

**Comment by perssonmathias** [comment]
@jfarcand atmosphere-runtime 2.4.8 -> 2.5.4 and atmosphere-spring 2.4.21 -> 2.5.0

**Comment by jfarcand** [comment]
Can you try 2.5.4 with atmosphere-spring 2.4.21

**Comment by perssonmathias** [comment]
@jfarcand That gets rid of this specific error. But instead I get several of these errors in the log:

SEVERE [main] org.atmosphere.inject.InjectableObjectFactory.configure

The reason for going from 2.4.21 to 2.5.0 was to get rid of this error (which it did, but replaced it with another).

**Comment by jfarcand** [comment]
@perssonmathias Can you reproduce using the Spring's sample (see atmosphere-samples git repo)

**Comment by perssonmathias** [comment]
@jfarcand The issue is reproducible using the Spring sample if you include atmosphere-spring as a dependency.

**Comment by seamusmac** [comment]
@jfarcand This issue should be in the extensions projects. 
I did upgrade to latest of everything and noticed the same issue. 

PR created at https://github.com/Atmosphere/atmosphere-extensions/pull/244

It should support Spring 3, 4 & 5

**Comment by jfarcand** [comment]
@seamusmac fixed. Thanks!
