### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()

### ISSUE THREAD

**Issue by MichalChomo** [Atmosphere/atmosphere#2385]
**Atmosphere version: 2.5.9**
**Nettosphere version: 3.1.1**
**Netty version: 4.1.43.Final**

Tested on OpenJDK 8 and Oracle Java 8:
```
openjdk version "1.8.0_202-release"
OpenJDK Runtime Environment (build 1.8.0_202-release-b1491)
OpenJDK 64-Bit Server VM (build 25.202-b1491, mixed mode)
```
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

I am getting:

```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.atmosphere.websocket.WebSocket.close(WebSocket.java:322)
	at org.atmosphere.container.NettyCometSupport.complete(NettyCometSupport.java:92)
	at org.atmosphere.container.NettyCometSupport.complete(NettyCometSupport.java:36)
	at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:815)
	at org.atmosphere.cpr.AtmosphereResourceImpl.close(AtmosphereResourceImpl.java:909)
```

when using Websocket and trying to close `AtmosphereResource`.

There already was an [issue](https://github.com/Atmosphere/atmosphere/issues/2380) with ByteBuffer, fixed by [this commit](https://github.com/Atmosphere/atmosphere/commit/437e3a2a142deb944e82e9d582de691719fac66d). Could this be fixed similarly in `WebSocket` class?

**Comment by jfarcand** [comment]
Merged, thanks. I will cut a new release asap

**Comment by jfarcand** [comment]
Release done. Thanks again!

**Comment by MichalChomo** [comment]
Hi, thanks for looking at this. Is the PR really merged? I still see it as Open.
