### ISSUE TITLE
[Tomcat 7.0.x]  Outbound connection not closed on WebSocketException

### ISSUE THREAD

**Issue by azolotko** [Atmosphere/atmosphere#2398]
Atmosphere uses `WebSocketException` to wrap exceptions occurred in `DefaultWebSocketProcessor`: https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.5.x/modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java#L577

`WebSocketException` extends `java.lang.Exception`: https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.5.x/modules/cpr/src/main/java/org/atmosphere/websocket/WebSocketProcessor.java#L124

Unfortunately,  `StreamInbound.onData(...)` in Tomcat 7.0.x only catches `MalformedInputException`, `UnmappableCharacterException`, and `IOException`:
https://github.com/apache/tomcat/blob/7.0.x/java/org/apache/catalina/websocket/StreamInbound.java#L155-L168

When, for example, a `java.nio.charset.MalformedInputException` gets thrown, it gets wrapped in a `WebSocketException`, which `StreamInbound` doesn't handle and therefore doesn't call `closeOutboundConnection` (`WsOutbound` is not closed and `doOnClose` is not executed):
```
ERROR c.e.w.OcppEventHandler$$anon$1  - WebSocket error
org.atmosphere.websocket.WebSocketProcessor$WebSocketException: java.nio.charset.MalformedInputException: Input length = 1
	at org.atmosphere.websocket.DefaultWebSocketProcessor.handleException(DefaultWebSocketProcessor.java:580)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:566)
	at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:104)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:186)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:134)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:83)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:587)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1686)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:832)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:561)
	... 9 common frames omitted
```

**Comment by azolotko** [comment]
Giving it more thought, we have control over what to do in our `onError` handler and can do the right thing in our code,
