### ISSUE TITLE
Unable to deploy websocket example app. on glassfish 4/5

### ISSUE THREAD

**Issue by itgabrut** [Atmosphere/atmosphere#2419]
I am trying to deploy Atmosphere example application:
[https://mvnrepository.com/artifact/org.atmosphere.samples/atmosphere-spring-websocket/2.5.13](https://mvnrepository.com/artifact/org.atmosphere.samples/atmosphere-spring-websocket/2.5.13)

It seems that application gets initialized twice. 
Once from WebModule -> CallServletContainerInitializer 
Second time from WebModule -> loadOnStartup -> initServlet -> MeteorServlet
While trying to register jsr356 endpoint for second initialization, the error occurs:
```
java.lang.IllegalStateException: Not in 'deploy' scope.
	at org.glassfish.tyrus.server.TyrusServerContainer.addEndpoint(TyrusServerContainer.java:195) ~[tyrus-server.jar:na]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:74) ~[atmosphere-runtime-2.5.13.jar:2.5.13]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40) ~[atmosphere-runtime-2.5.13.jar:2.5.13]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_181]
```

TyrusServerContainer has a method doneDeployment, that getting called after first iniializationt, and before second
 ``` 
   public void doneDeployment() {
        this.canDeploy = false;
    }
```
There is no way to register jsr endpoint after this flag set to false.

**Atmosphere Info**
 [https://mvnrepository.com/artifact/org.atmosphere.samples/atmosphere-spring-websocket/2.5.13](https://mvnrepository.com/artifact/org.atmosphere.samples/atmosphere-spring-websocket/2.5.13)
 

**Systems (please complete the following information):**
 - Java version 8
 - Glassfish 4, Glassfish 5

**Additional context**

**Comment by jfarcand** [comment]
@itgabrut Please share a test case on Github demonstrating the issue. I am not aware of such issue. Make sure you are using latest version of Atmosphere :-)
