### ISSUE TITLE
Jetty 10 Runtime Error

### ISSUE THREAD

**Issue by tkohlman** [Atmosphere/atmosphere#2455]
**Describe the bug**

ClassNotFoundException occurs with Jetty 10.

> Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.continuation.ContinuationListener
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3137) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3342) ~[?:?]
        at java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[?:?]
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:236) ~[atmosphere-runtime-2.7.3.jar:?]
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveNativeCometSupport(DefaultAsyncSupportResolver.java:319) ~[atmosphere-runtime-2.7.3.jar:?]
        at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:299) ~[atmosphere-runtime-2.7.3.jar:?]
        at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2089) ~[atmosphere-runtime-2.7.3.jar:?]
        at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:909) ~[atmosphere-runtime-2.7.3.jar:?]
        ... 42 more

**Atmosphere Info**
  - atmosphere-runtime 2.7.3

**Expected behavior**
Are there plans to support Jetty versions 10 and 11?

**Comment by jfarcand** [comment]
@tkohlman yes, it is, but I suspect they have removed completely their native implementation. Are you using de `useNative` properties by any chance? An alternative is to add 
```xml
		<dependency>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-continuation</artifactId>
				<version>${jetty.version}</version>
		</dependency>
```
in your pom.xml

**Comment by tarzdorf** [comment]
We encounter the same issue currently. What parameter is the "useNative"? Is it for the Jetty configuration?

**Comment by tkohlman** [comment]
I am using embedded jetty without a pom.xml file, and the only parameter I had set previously was the following:
`context.setInitParameter("org.atmosphere.cpr.AtmosphereInterceptor","org.atmosphere.client.TrackMessageSizeInterceptor");`

Explicitly setting useNative to false yields the same ClassNotFoundException:
`context.setInitParameter("org.atmosphere.useNative", "false");`

Attempting to force JSR 356 yields the same ClassNotFoundException:
`context.setInitParameter("org.atmosphere.websocket.suppressJSR356", "false");`
`context.setInitParameter("org.atmosphere.cpr.asyncSupport", "org.atmosphere.container.JSR356AsyncSupport");`

The reflection logic appears to be selecting Jetty7CometSupport (which uses Jetty continuation) as the implementation of the AsyncSupport interface. I have not discovered a way to provide an implementation of AsyncSupportResolver that forces use of JSR356AsyncSupport.

I am tracing through the init logic attempting to get something to work, but any other suggestions would be appreciated.

**Comment by jfarcand** [comment]
@tkohlman @tarzdorf I've updated the [atmosphere-samples](https://github.com/Atmosphere/atmosphere-samples/tree/updates/jetty10_jdk11) workspace to Jetty `10.0.7` and everything works as expected. Please take a look at this [sample for example](https://github.com/Atmosphere/atmosphere-samples/tree/updates/jetty10_jdk11/samples/chat) and let me know if they work for you.

**Comment by jfarcand** [comment]
@tkohlman Is https://github.com/Atmosphere/atmosphere-samples/tree/updates/jetty10_jdk11/samples/embedded-jetty-websocket-chat working for you?

**Comment by tkohlman** [comment]
[https://github.com/Atmosphere/atmosphere-samples/tree/updates/jetty10_jdk11/samples/embedded-jetty-websocket-chat](url) does not work for me. I see the following exception:

> 10:55:51.055 [qtp597393630-25] ERROR o.atmosphere.cpr.AtmosphereFramework - Failed to initialize Atmosphere Framework
java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/servlet/WebSocketCreator
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137) ~[na:na]
	at java.base/java.lang.Class.getConstructor0(Class.java:3342) ~[na:na]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[na:na]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:253) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereFramework.doInitParams(AtmosphereFramework.java:1448) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereFramework.doInitParams(AtmosphereFramework.java:1423) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:873) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:833) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:76) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:83) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:79) ~[atmosphere-runtime-2.7.2.jar:na]
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:74) ~[atmosphere-runtime-2.7.2.jar:na]

I believe this is because some of the jetty websocket classes were renamed in Jetty 10 and AbstractJetty9AsyncSupportWithWebSocket and other classes still use the old class names.

See [https://www.eclipse.org/lists/jetty-users/msg09742.html](url)

> == Classes Renamed ==
WebSocketCreator -> JettyWebSocketCreator
ServletUpgradeRequest -> JettyServerUpgradeRequest
ServletUpgradeResponse -> JettyServerUpgradeResponse
WebSocketServlet -> JettyWebSocketServlet
WebSocketServletFactory -> JettyWebSocketServletFactory

> == Package Change for these Classes ==
org.eclipse.jetty.websocket.servlet  ->  org.eclipse.jetty.websocket.server

**Comment by tkohlman** [comment]
I have ported the Jetty 9 support code to Jetty 10 here: https://github.com/tkohlman/atmosphere/commit/e2cb4d0a061f1b89773d3862364efedf83d23e20

- I added a null check in AtmosphereRequestImpl isAsyncStarted() because Jetty 10 calls this before onWebSocketConnect(), meaning the resource is not yet created (NullPointerException).
- I did not address auto-discovery of Jetty 10 via reflection.
- I do not have experience with mvn builds or pom.xml files so I am probably not the best person to take the code I've written and create a PR.
- Jetty 11 is identical to Jetty 10 except that it uses the new jakarta.* packages instead of the javax.* packages. I believe Tomcat 10 also uses the new jakarta.* packages. I'm not sure how atmosphere should address supporting both, but it would nice if it did.

**Comment by jfarcand** [comment]
@tkohlman Can you do a pull request and mark it as draft. That way we can collaborate on a branch together.

**Comment by rofrance** [comment]
Hi all,
I am also having the same issues that @tkohlman reported one year ago. I am running latest Atmosphere 2.7.4 and Jetty 10.0.7 and was wondering if there is anything specific that I need to do to avoid the error:

`javax.servlet.ServletException: java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/servlet/WebSocketCreator
 	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:955)
 	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
 	at org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:75)
 	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:84)
 	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:80)
 	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:75)
 	...`

I wasn't able to find any examples or suggestions for running Atmosphere under Jetty10 or 11. For now I am trying to keep it simple and avoid the jakarta renames by using Jetty10.
Can you please advise?

Thanks in advance!

**Comment by jfarcand** [comment]
@rofrance @tkohlman Fixed in 2.7.5

**Comment by rofrance** [comment]
Thanks for replying and fixing this so quickly @jfarcand ! I'll test the new version as soon as possible and let you know how it goes.

**Comment by tarzdorf** [comment]
Thanks for the Fix. We will also try the new version then with Jetty 10.

**Comment by nopainsnogains12** [comment]
@jfarcand 
We are also using Atmosphere and we are using 2.7.6 (upgraded from 2.4.32) now with Jetty10 upgraded from Jetty 9.4. I can confirm that the original "ClassNotFoundException" issue has been solved. Thanks a lot!
But, we have another issue which is that the websocket functionality is NOT working anymore from Atmosphere with the log "**Websocket protocol not supported (CLS=o.a.cpr.AsynchronousProcessor)**". According to my quick check, it looks that the PR change https://github.com/tkohlman/atmosphere/commit/e2cb4d0a061f1b89773d3862364efedf83d23e20 prepared by @tkohlman  seems to be needed to enable atmosphere to automatically discover Jetty 10 support. Could you share why this PR is NOT merged? Can we expect the similar fix to support Jetty 10 with atmosphere websocket functionality? Looking forward to your early reply! Thanks!.
Wenbin

**Comment by rofrance** [comment]
Hi @jfarcand , 

I finally had time to test the latest version of atmosphere 2.x (2.7.7) with Jetty 10.0.11 and I am getting the "WARN :oac.AsynchronousProcessor:qtp2115628016-27: Websocket protocol not supported" message that @nopainsnogains12 is also seeing. Atmosphere is currently only working in long polling for me.

Would it be possible to fix it? Could it be related to some configuration or is there more that we need to merge from @tkohlman 's PR?

Thanks in advance!
Roberto

**Comment by nopainsnogains12** [comment]
@tkohlman @tarzdorf @rofrance @jfarcand 
Dear All, just for your information, after struggling longer without actual progress with Atmosphere, and as already communicated above in my original thread as well, it is obviously that the Jetty 10 is NOT supported in Atmosphere 2.7.7 the same way as it was for Jetty 9.x in Atmosphere 2.4.*. Finally, our project can NOT afford to keep waiting for the no-deadline potential support from Atmosphere, we finally decided to give up the usage of Atmosphere and adopted Jetty websocket to continue our work. Just FYI. Thanks!

**Comment by jfarcand** [comment]
@nopainsnogains12 @rofrance Sorry I was on vacation :-) That's sad you were not able to make it work. Like I've said I am using the Atmosphere's chat sample and everything works as expected -> https://github.com/Atmosphere/atmosphere-samples/tree/updates/jetty10_jdk11/samples/chat . @rofrance if you can share a test/sample that demonstrate the issue, I will take a look.

**Comment by cliviu** [comment]
> @nopainsnogains12 @rofrance Sorry I was on vacation :-) That's sad you were not able to make it work. Like I've said I am using the Atmosphere's chat sample and everything works as expected -> https://github.com/Atmosphere/atmosphere-samples/tree/updates/jetty10_jdk11/samples/chat . @rofrance if you can share a test/sample that demonstrate the issue, I will take a look.

@jfarcand the link from this issue is dead. It looks like all the examples are with Jetty9

**Comment by rofrance** [comment]
Getting back to this now that we're forced to upgrade to a newer Jetty, thanks to [this comment](https://github.com/Atmosphere/atmosphere/issues/2477#issuecomment-1122509599) from @nopainsnogains12, I finally found the solution to "WARN :oac.AsynchronousProcessor:qtp2115628016-27: Websocket protocol not supported" in a few minutes! It is just making sure that "org.atmosphere.websocket.suppressJSR356" is set to false. Thanks all!
