### ISSUE TITLE
Jetty 9.4+/10 is throwing and exception when javax.session.Session.addMessageHandler(MessageHandler handler) is called

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#2478]
```java
09:15:38.744 ERROR [qtp222624801-17] o.a.c.JSR356Endpoint [JSR356Endpoint.java:271]
java.lang.IllegalStateException: Unable to find Decoder for type: interface javax.websocket.MessageHandler$Whole
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.addMessageHandler(JavaxWebSocketFrameHandler.java:419) ~[na:na]
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketSession.addMessageHandler(JavaxWebSocketSession.java:132) ~[na:na]
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketSession.addMessageHandler(JavaxWebSocketSession.java:152) ~[na:na]
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:259) ~[atmosphere-runtime-2.7.7-SNAPSHOT.jar:na]
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.onOpen(JavaxWebSocketFrameHandler.java:175) ~[na:na]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$onOpen$6(WebSocketCoreSession.java:410) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1463) ~[na:na]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1482) ~[na:na]
	at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212) ~[na:na]
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onOpen(WebSocketCoreSession.java:410) ~[na:na]
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onOpen(WebSocketConnection.java:542) ~[na:na]
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:451) ~[na:na]
	at org.eclipse.jetty.server.HttpConnection.upgrade(HttpConnection.java:419) ~[na:na]
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:450) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:968) ~[na:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:485) ~[na:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[na:na]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[na:na]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[na:na]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[na:na]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[na:na]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[na:na]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[na:na]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[na:na]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407) ~[na:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[na:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by jfarcand** [comment]
Not an issue, a regression added to 2.7.7-SNAPSHOT
