### ISSUE TITLE
WebSocket enabled but implementing different transport protocol

### ISSUE THREAD

**Issue by billyyarosh** [Atmosphere/atmosphere#294]
My WebSocket connection is successful when using Google Chrome. When using Mozilla Firefox 10.0.1, I get the following error on front end:

> Firefox can't establish a connection to the server at ws://localhost:9000/servlet-context/notifications?X-Atmosphere-tracking-id=00def55b-070e-8fc8-062b-503647681dbd&X-Atmosphere-Framework=0.9&X-Atmosphere-Transport=websocket&X-Cache-Date=0.
> 
> return new MozWebSocket(location);
> 
> jquery...here.js (line 346)
> Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent).
> jquery...here.js (line 1659)
> Websocket closed, wasClean: false
> Websocket failed. Downgrading to Comet and resending

Now it attempts to the servlet request with streaming.

> Invoking request callbacks
> jquery...here.js (line 1659)
> response.state: opening
> jquery...here.js (line 1659)
> response.transport: streaming
> jquery...here.js (line 1659)
> response.responseBody:
> jquery...here.js (line 1659)
> response.responseBody is null - ignoring.
> search (line 156)
> Max re-connection reached.

And then Tomcat I get this stack trace in 

```
     java.lang.IllegalStateException: Not supported.
at org.apache.catalina.connector.Request.startAsync(Request.java:1664)
at org.apache.catalina.connector.Request.startAsync(Request.java:1657)
at org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:1023)
at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:364)
at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:364)
at org.atmosphere.cpr.AtmosphereRequest.startAsync(AtmosphereRequest.java:512)
at org.atmosphere.container.Servlet30CometSupport.suspend(Servlet30CometSupport.java:140)
at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:104)
at org.atmosphere.container.Tomcat7AsyncSupportWithWebSocket.service(Tomcat7AsyncSupportWithWebSocket.java:90)
at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1146)
at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:293)
at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:279)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:101)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
.
.
.
```

Also, shouldn't websockets work on Firefox?

**Comment by venkat-rknowsys** [comment]
**keaplogik**
> Ok, the jquery update fixes that issue

what is the jQuery version you updated?

I am using jQuery v1.10.2. It works o my localhost but didn't work on the stagig server test.xxxx.com
on any browser. The console reads 

Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent).
Websocket closed, wasClean: false
