### ISSUE TITLE
Regression: Jetty 7.x java.lang.NoSuchMethodError with WebSocket

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#89]
2011-11-29 08:10:18.353:WARN:oejs.ServletHandler:Error for /atmosphere-jquery-pubsub/pubsub/aaaaa
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getServletContext()Ljavax/servlet/ServletContext;
    at org.atmosphere.container.JettyWebSocketHandler$JettyRequestFix.<init>(JettyWebSocketHandler.java:231)
    at org.atmosphere.container.JettyWebSocketHandler.<init>(JettyWebSocketHandler.java:62)
    at org.atmosphere.container.JettyWebSocketUtil$1.doWebSocketConnect(JettyWebSocketUtil.java:87)
    at org.eclipse.jetty.websocket.WebSocketFactory.acceptWebSocket(WebSocketFactory.java:310)
    at org.atmosphere.container.JettyWebSocketUtil.doService(JettyWebSocketUtil.java:61)
    at org.atmosphere.container.JettyCometSupportWithWebSocket.service(JettyCometSupportWithWebSocket.java:78)
    at org.atmosphere.cpr.AtmosphereServlet.doCometSupport(AtmosphereServlet.java:1183)
    at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:1151)
    at org.atmosphere.cpr.AtmosphereServlet.doGet(AtmosphereServlet.java:1137)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)

**Comment by KalpeshJ** [comment]
Please share how you have fixed it.

**Comment by jfarcand** [comment]
@KalpeshJ Click on the link above :-)

**Comment by KalpeshJ** [comment]
Thanks:)
