### ISSUE TITLE
failed to create comet support class

### ISSUE THREAD

**Issue by thomasverbeke** [Atmosphere/atmosphere#912]
Hey;
I'm trying to run the chat sample (not just run it using the war file).
However when connecting to the server I run into this problem.

"java.lang.IllegalArgumentException: Comet support class org.atmosphere.container.JettyAsyncSupportWithWebSocket has bad signature."

I'm using run jetty run and maven eclipse plugin.

my maven dependencies are correct as far as I know. 

``` java
12:23:37.027 [qtp1561244285-12] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
12:23:37.053 [qtp1561244285-12] DEBUG o.atmosphere.cpr.AtmosphereFramework - Atmosphere's Service Annotation Not Supported. Please add https://github.com/rmuller/infomas-asl as dependencies or your own AnnotationProcessor to support @Service
12:23:37.066 [qtp1561244285-12] INFO  o.atmosphere.cpr.AtmosphereFramework - Auto detecting atmosphere handlers /WEB-INF/classes/
12:23:37.067 [qtp1561244285-12] INFO  o.atmosphere.cpr.AtmosphereFramework - Auto detecting WebSocketHandler in /WEB-INF/classes/
12:23:37.067 [qtp1561244285-12] INFO  o.atmosphere.cpr.AtmosphereFramework - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
12:23:37.081 [qtp1561244285-12] ERROR o.a.cpr.DefaultAsyncSupportResolver - failed to create comet support class: class org.atmosphere.container.JettyAsyncSupportWithWebSocket, error: null
12:23:37.089 [qtp1561244285-12] ERROR o.atmosphere.cpr.AtmosphereFramework - Failed to initialize Atmosphere Framework
java.lang.IllegalArgumentException: Comet support class org.atmosphere.container.JettyAsyncSupportWithWebSocket has bad signature.
    at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:233) ~[atmosphere-runtime-1.0.10.jar:1.0.10]
    at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:296) ~[atmosphere-runtime-1.0.10.jar:1.0.10]
    at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:284) ~[atmosphere-runtime-1.0.10.jar:1.0.10]
    at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:1163) ~[atmosphere-runtime-1.0.10.jar:1.0.10]
    at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:534) ~[atmosphere-runtime-1.0.10.jar:1.0.10]
    at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:191) [atmosphere-runtime-1.0.10.jar:1.0.10]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:516) [jetty-servlet-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:398) [jetty-servlet-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:642) [jetty-servlet-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445) [jetty-servlet-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564) [jetty-security-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1054) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372) [jetty-servlet-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:988) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.Server.handle(Server.java:410) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:245) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.server.HttpConnection$1.run(HttpConnection.java:75) [jetty-server-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:597) [jetty-util-9.0.0.M3.jar:9.0.0.M3]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:528) [jetty-util-9.0.0.M3.jar:9.0.0.M3]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_13]
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_13]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_13]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_13]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525) ~[na:1.7.0_13]
    at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:229) 
```

pom.xml

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.atmosphere</groupId>
  <artifactId>chat_test</artifactId>
  <packaging>war</packaging>
  <version>1.0.10</version>
  <name>chat_test Maven Webapp</name>
  <url>http://maven.apache.org</url>
  <build>
    <finalName>chat_test</finalName>
  </build>

  <dependencies>
    <dependency>
        <groupId>org.atmosphere</groupId>
        <artifactId>atmosphere-runtime</artifactId>
        <version>1.0.10</version>
    </dependency>
    <dependency>
        <groupId>org.atmosphere</groupId>
        <artifactId>atmosphere-jquery</artifactId>
        <version>1.0.10</version>
        <type>war</type>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>1.0.9</version>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-core</artifactId>
        <version>1.0.9</version>
    </dependency>
    <dependency>
       <groupId>eu.infomas</groupId>
       <artifactId>annotation-detector</artifactId>
       <version>3.0.0</version>
    </dependency>
    <dependency>
        <groupId>org.codehaus.jackson</groupId>
        <artifactId>jackson-mapper-asl</artifactId>
        <version>1.9.12</version>
    </dependency>
    <dependency>
        <groupId>org.eclipse.jetty.websocket</groupId>
        <artifactId>websocket-server</artifactId>
        <version>9.0.0.M3</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by mchaudhary** [comment]
Facing similar problem. I am getting following error 
12:51:48.554 [main] ERROR o.a.cpr.DefaultAsyncSupportResolver - Failed to create comet support class: class org.atmosphere.container.JettyServlet30AsyncSupportWithWebSocket, error: java.lang.reflect.InvocationTargetException

I am using Nettosphere. I do have a something in path which contains Jetty. I am using following in pom.xml so version of Atmosphere is also 2.3.1
<properties>
    <nettosphere-version>2.3.1</nettosphere-version>
    <atmosphere-version>2.3.1</atmosphere-version>
    <netty-version>3.10.2.Final</netty-version>
  </properties>

Is there a recommendation ?

**Comment by mchaudhary** [comment]
This causes nettosphere to not start.

**Comment by jfarcand** [comment]
@mchaudhary Please use the mailing list for question. Your issue: you have jetty's jar in the classpath, so either set the AsyncSupport class in web.xml, or remove Jetty. Please ask question on the ML

https://groups.google.com/group/atmosphere-framework?pli=1

Thanks!
